---
output: 
  pdf_document:
      latex_engine: pdflatex
      template: cv-latex.tex
  md_document:
    variant: gfm
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding,
         output_format = "all") })
geometry: margin=.7in
title: "Extended CV"
author: JESSICA L. BURNETT
orcid:  0000-0002-0896-5099
fontawesome: yes
email: jburnett@usgs.gov
# github: trashbirdecology
phone: "+1 720-730-0974"
# updated: no
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue(munsell)
linkcolor: maroon
linkedin: burnettjl
jobtitle: Research Ecologist & Mendenhall Postdoctoral Fellow
---

# STEM Outreach 
## Community Involvement  
- Letters to a Pre-scientist (2018-present)
- Skype a Scientist, Virtual (2017-present)
- Secured grant to develop on-site nature trail and wildlife viewing opportunities at the Reichert House in Florida (2014-15)
- Organized hands-on wildlife handling events for students of the Reichert House, Gainesville, FL (2014-15)
- Live bird banding demonstrations and bird watching activities for K-12 students, A Girls' Place, Gainesville, FL (2013-15)
- Science, mathematics, and reading tutor for middle and high school students, Friends of the Micanopy Library, FL (2011-13)
- Learning assistant and tutor for mathematics students, Valencia Community College, Orlando, FL  (2008-10) 

## Blogs
- [Connecting to nature and understanding ecosystem services: urban perspective](https://envirobites.org/2017/10/17/connecting-to-nature-and-understanding-ecosystem-services-the-urban-perspective/), Envirobites
- [Big data, big problems](http://resilience2017.org/blog/big-data-big-problems/) 
- [Panarchy in the Anthropocene](http://resilience2017.org/blog/panarchy-in-the-anthropocene/) - [Regime shifts, traps and how to deal with them](http://resilience2017.org/blog/regime-shifts-traps-and-how-to-deal-with-them/)
- [Connecting to nature and understanding ecosystem services: the urban perspective](http://resilience2017.org/blog/connecting-to-nature-and-understanding-ecosystem-services-the-urban-perspective/)
- [Leadership resilience and your workplace](http://resilience2017.org/blog/leadership-resilience-and-your-workplace/)

## Podcasts  
- [House Sparrow declines in North America, Urban Wildlife Podcast](http://www.urbanwildlifecast.com/?p=139)   

# Service 
## Department of Interior  
- Co-author, FEVS Analysis Team for Core Science Systems Science Analytics and Synthesis (2021)
- Member, Federal Advisory Committee for Avian Knowledge Network (2019-present)
- Member, Communications and Marketing Committee for the North American Breeding Bird Survey 2020 Action Plan (2020-21)

## Peer Review Activity  
- Journal articles: *Bioinvasions Records* (1), *Conservation Biology* (1), *Ecological Informatics* (6), *Ecological Modelling* (4), *Journal of Molluscan Studies* (2), *Landscape and Urban Planning* (2), *PLOS One* (1), *Wilson Journal of Ornithology* (3)
- Code and software: *Journal of Open Source Software* (3), *ReScience* (1)
- Department of Interior: Abstracts (2), Research Articles (2), Software/code (1), Reports (2)

## Service at the University of Nebraska-Lincoln
- Conference abstract reviewer, Ecological Society of America (2021)
- Co-founder, Natural Resources Diversity Initiative committee, School of Natural Resources (2017)
- [Faculty Advisory Committee](http://snr.unl.edu/employeeinfo/people/committee/facultyadvisory.asp), School of Natural Resources (2016-18)
- Student Representative, Committee for Urban Forestry Professor of Practice Position, University of Nebraska-Lincoln (2016-17 
- Co-founder, [Institutional membership to the Association for Women in Science](http://news.unl.edu/newsrooms/today/article/university-is-institutional-partner-with-association-for-women-in-science/) (2016
- Digital Team, School of Natural Resources (2016
- Organizer, Association for Women in Science [Mentor Workshop](http://snr.unl.edu/registration/AWISMentor/MentorMenteeRegistrationAttendanceCap.aspx?utm_source=Google&utm_medium=email&utm_term=&utm_content=&utm_campaign=AWIS+Workshop) (2016)
- Seminar Coordinator, School of Natural Resources  (2016)
- Department Representative, UNL Graduate Student Association  (2015 - 16)
- Student Liaison, Urban Ecosystem Ecology Section, Ecological Society of America (2015 - 16)

## Service at the University of Florida
- Chair, Student Travel Grant Award Committee, Dept. of Wildlife Ecology and Conservation (2012-13)
- Contributed feedback on applicants to 3 faculty positions in the department, University of Florida (2012-13)
- Treasurer, Student Graduate Association, Dept. of Wildlife Ecology and Conservation, 
(2011-13)
- Member, Natural Resources Diversity Initiative (2011-13)
- Member, EcoThinkTank Graduate Student Group (2011-13)
