---
output: pdf_document
---
#Jessica L. Burnett
### Urban Ecology | Computational Ecology | Open Science
## Education
**University of Nebraska-Lincoln in Lincoln, NE**  
&nbsp;&nbsp;&nbsp;&nbsp;Ph.D. (*expected* 2019) Natural Resource Sciences and Applied Ecology    
**University of Florida in Gainesville, FL**  
&nbsp;&nbsp;&nbsp;&nbsp;M.Sc. (2015) Wildlife Ecology and Conservation      
&nbsp;&nbsp;&nbsp;&nbsp;B.Sc. (2013) Wildlife Ecology and Conservation   

## Research Experience  
**Graduate Research Assistant** (2015-Present)    
Nebraska Cooperative Fish and Wildlife Research Unit | University of Nebraska-Lincoln    
* Explore methods for detecting and predicting regime shifts on long-term and spatially explicit data.   
* Identify indicator species for ecosystem regime shift prediction.  
* Maintain clear communication with international collaborators.  
* Work with military base scientists to collect data.   
* Write quarterly reports for Department of Defense.  

**Graduate Research Assistant** (2013-2015)    
Department of Wildlife Ecology and Conservation | University of Florida  
* Use of open-source data to monitor invasive species' population trends.  
* Development of occupancy models of non-native bird speces in urban areas.  

**GIS and Avian Ecology Intern** (2013)    
Fish and Wildlife Research Institute | Florida Fish and Wildlife Research Conservation Commission    
* Investigated effects of agriculture and urbanization on American Kestrel (*Falco sparverius*) nest success.   

**Research Assistant** (2012-2013)     
Sieving Avian Ecology and Conservation Lab | University of Florida    
* Investigated alignment of predation risk perception and predation risk of small forest birds.  
* Managed seasonal bird danding database and banding supplies.  

**Smithsonian Fellow and Florida Crew Leader** (2011-2013)  
Neighborhood Nestwatch Program  | Smithsonian Migratory Bird Center  
* Targeted capture and banding of select species in participants' backyards.  
* Banding demonstrations at local youth organizations.  
* Organized and trained banding technicians.  

**Project Volunteer** (2012)    
Ordway Lab of Ecosystem Conservation | Univeristy of Florida  
* Transcribed voice-recorded, behavioral foraging data.
* Identified louse from lowland manakins and flycatcher specimens.  

## Peer-reviewed Publications
[1]  **Burnett, J.L.** and Moulton, M.P. 2015. Recent trends in House Sparrow (*Passer domesticus*) distribution and abundance in Gainesville, Alachua County, Florida. *Florida Field Naturalist* 43(4):167-172.   

[2]  **Burnett, J.L.** and Sieving, K.E. Accepted with minor revisions. Songbird distress call as a detection enhancement method and application to Red-shouldered Hawks (*Buteo lineatus*). *Florida Field Naturalist*.      

[3]  **Burnett, J.L.**, Allen, C.R., Brown, M.B., and Roberts, C.R. *Accepted*. Eurasian Tree Sparrow (*Passer montanus*) range expansion in North America.  *Biological Invasions*.     

[4] Allen, C.R., Birge, H.B., Bartlet-Hunt, S.L., Bevans, R.A., **Burnett, J L.** , Cosens, B.A., Cai, X., Garmestani, A.S., Linkov, I., Scott, E.A., Solomon, M.D., and Uden, D. *Accepted with revisions*. Avoiding decline: Fostering resilience and sustainability in midsize cities. *Sustainability*   

## Invited Talks

[1] Invited talk  Decline of the Once-Ubiquitous House Sparrow in North America. *Nerbraska Invasive Species Council*, Lincoln, N.E., 2015.

[2] Guest lecture and lab session, *Using Citizen Science Data in Avian Invasion Ecology*, in undergraduate course, *Ecology of Avian Invasions*, 2013. Interactive discussion and instruction on finding and utilizing open-sourced data to understand the dynamics and ecology of avian invasions.

## Presentations
[1] **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Using Big Data to Detect Regime Shifts in Space and Time. *North American Ornithological Conference VI*, Poster presentation. Smithsonian Migratory Bird Institute, Washington, D.C., 2016

[2] **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? Southeastern Ecology and Evolution Conference, Oral presentation. University of Georgia, Athens, GA, 2015  

[3] **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M.L., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? *American Ornithologists' Union and Cooper Ornithological Society Annual Meeting*, Poster presentation. Norman, OK, 2015.

[4] **Burnett, J.L.**, Moulton, M.P., and Sieving, K.E. House sparrow: the decline of a once ubiquitous, invasive species. *Florida Chapter of The Wildlife Society Annual Conference*, Poster presentation. Safety Harbor, FL, 2014.

[5] **Burnett, J.L.** and Sieving, K.E. Detecting birds of prey using tufted titmouse distress calls. *USGS Florida Cooperative Fish and Wildlife Research Unit Committee Meeting*, Poster presentation. Gainesville, FL, 2013.

[6] **Burnett, J.L.** and Sieving, K.E. Do actual and perceived risks of small forest birds align? *Florida Ornithological Society Conference, Oral presentation*, St. Petersburg, FL, 2013.

[7] **Burnett, J.L.** and Sieving, K.E. Perceived predation risks of small forest birds. *Association of Field Ornithologists Annual Conference*, Poster presentation. Venus, FL, 2013.

# Service
####At the University of Nebraska-Lincoln       
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Liaison, [Faculty Advisory Committee](http://snr.unl.edu/employeeinfo/people/committee/facultyadvisory.asp), School of Natural Resources, University of Nebraska-Lincoln    
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Organizer, Association for Women in Science [Mentor Workshop](http://snr.unl.edu/registration/AWISMentor/MentorMenteeRegistrationAttendanceCap.aspx?utm_source=Google&utm_medium=email&utm_term=&utm_content=&utm_campaign=AWIS+Workshop), University of Nebraska-Lincoln  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Faculty Search Committee, [Urban and Community Forester](http://wfscjobs.tamu.edu/jobs/urban-and-community-forestry-professor-of-practice-university-of-nebraska-lincoln/), University of Nebraska-Lincoln  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Seminar Coordinator](http://unlcms.unl.edu/snr/gsa/snr-gsa-seminar-coordinators), School of Natural Resources, University of Nebraska-Lincoln     
2015-16&nbsp;&nbsp;&nbsp; &nbsp;Founder & President, Natural Resources Diversity Initiative, University of Nebraska-Lincoln    
2015-16&nbsp;&nbsp;&nbsp; &nbsp;Department Representative Representative, Graduate Student Association, University of Nebraska-Lincoln        
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founder, Affiliate Chapter of the Association for Women in Science, University of Nebraska-Lincoln    

####To the Profession    

2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Planning Committee for [Inclusive Ecology Section](http://www.esa.org/inclusive-ecology/), Ecological Society of America    
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reviewer, Wilson Journal of Ornithology    
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Liaison, [Urban Ecosystem Ecology Section](http://www.esa.org/urbanecology/),  Ecological Society of America   

##Grants
####Research   
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IFAS Extension Internship for Undergraduate Research, University of Florida __$2,200__  
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ordway-Swisher Biological Station Undergraduate Research, University of Florida __$550__ 

####Travel   

2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Nelson Memorial Fellowship](http://newsroom.unl.edu/announce/snr/5519/31162), Univeristy of Nebraska-Lincoln __$900__  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Center for Great Plains Studies, Univeristy of Nebraska-Lincoln __$750__   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;American Ornithologists' Union __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NSF Diversity Award, Southeastern Ecology and Evolution Conference __$650__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graduate Student Council, University of Florida __$350__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of Research University of Florida __$500__  
2014&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of Dean, Institute of Food and Agricultural Sciences, University of Florida __$750__  

####&nbsp;&nbsp;&nbsp;Membership
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;American Ornithologists' Union Undergraduate Student Membership Award

## Honors & Awards
2016-18&nbsp;&nbsp;&nbsp; &nbsp;University of Nebraska Center for Great Plains Studies [Graduate Fellow](http://www.unl.edu/plains/graduate-fellows-program)       
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AAAS/Science Program for Excellence in Science Award     
2015-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Resilience Alliance Young Scholar  
2015-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Othmer Fellowship, University of Nebraska-Lincoln  **$24,000**     
2014&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2<sup>nd</sup> place, School of Natural Resources Elevator Speech Competition **$300**    
