---
output:
  pdf_document: default
---

#Jessica L. Burnett  
### Macroecology | Complex Systems | Quantitative Ecology  
## Education  
**University of Nebraska-Lincoln in Lincoln, NE**      
&nbsp;&nbsp;&nbsp;&nbsp;Ph.D. (*expected* 2019) Natural Resource Sciences and Applied Ecology    
**University of Florida in Gainesville, FL**  
&nbsp;&nbsp;&nbsp;&nbsp;M.Sc. (2015) Wildlife Ecology and Conservation      
&nbsp;&nbsp;&nbsp;&nbsp;B.Sc. (2013) Wildlife Ecology and Conservation   

## Professional Experience  
**Graduate Research Assistant** (2015-Present)    
Nebraska Cooperative Fish and Wildlife Research Unit | University of Nebraska-Lincoln    

**Graduate Teaching and Research Assistant** (2013-2015)    
Department of Wildlife Ecology and Conservation | University of Florida  

**Geospatial Analyst and Avian Ecology Intern** (2013)    
Fish and Wildlife Research Institute | Florida Fish and Wildlife Research Conservation Commission    

**Research Assistant and Lab Manager** (2012-2013)     
Sieving Avian Ecology and Conservation Lab | University of Florida    

**Smithsonian Fellow and Florida Crew Leader** (2011 and 2013)  
Neighborhood Nestwatch Program  | Smithsonian Migratory Bird Center  

## Peer-reviewed Publications

1.  **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Brown, M.B., and Moulton, M.P. 2017. Eurasian Tree Sparrow (*Passer montanus*) range expansion in North America. *Biological Invasions* 19(1): 5-9 doi:10.1007/s10530-016-1273-4  

1.  **Burnett, J.L.** and Sieving, K.E. 2016. Songbird distress call as a detection enhancement method and application to Red-shouldered Hawks (*Buteo lineatus*). *Florida Field Naturalist* 44(4):157-168      

1. Allen, C.R., Birge, H.B., Bartlet-Hunt, S.L., Bevans, R.A., **Burnett, J.L.** , Cosens, B.A., Cai, X., Garmestani, A.S., Linkov, I., Scott, E.A., Solomon, M.D., and Uden, D. 2016. Avoiding decline: Fostering resilience and sustainability in midsize cities. *Sustainability* 8(9):844-868 doi:10.3390/su8090844   

1.  **Burnett, J.L.** and Moulton, M.P. 2015. Recent trends in House Sparrow (*Passer domesticus*) distribution and abundance in Gainesville, Alachua County, Florida. *Florida Field Naturalist* 43(4):167-172   

## Agency Reports  

1. **Burnett , J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D. 2017. White Paper: Regime Shift Detection Using Fisher Information. Strategic Environmental Research and Development Program (SERDP), Department of Defense.  

1. Allen, C.R., Angeler, D.G., Twidwell, D., **Burnett , J.L.**, Roberts, C.P. 2017. Interim Report (RC 25-10): Global Change, Vulnerability, and Resilience: Management Options for an Uncertain Future. Strategic Environmental Research and Development Program (SERDP), Department of Defense.  

1. Twidwell D., Bielski, C.H., **Burnett , J.L.**, Donovan, V.M., Wonkka, C.L. 2017. Review of LANDFIRE Biophysical Settings Models (BpS) in the Great Plains. LANDFIRE Project. 

## Presentations

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Ecological Regimwe Shifts in the Central Great Plains. *Great Plains Symposium*, Oral presentation. Nebraska Innovation Campus, Lincoln, NE, 2017.

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Using Big Data to Detect Regime Shifts in Space and Time. *North American Ornithological Conference VI*, Poster presentation. Smithsonian Migratory Bird Institute, Washington, D.C., 2016

1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? Southeastern Ecology and Evolution Conference, Oral presentation. University of Georgia, Athens, GA, 2015  

1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M.L., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? *American Ornithologists' Union and Cooper Ornithological Society Annual Meeting*, Poster presentation. Norman, OK, 2015.

1. **Burnett, J.L.**, Moulton, M.P., and Sieving, K.E. House sparrow: the decline of a once ubiquitous, invasive species. *Florida Chapter of The Wildlife Society Annual Conference*, Poster presentation. Safety Harbor, FL, 2014.

1. **Burnett, J.L.** and Sieving, K.E. Detecting birds of prey using tufted titmouse distress calls. *USGS Florida Cooperative Fish and Wildlife Research Unit Committee Meeting*, Poster presentation. Gainesville, FL, 2013.

1. **Burnett, J.L.** and Sieving, K.E. Do actual and perceived risks of small forest birds align? *Florida Ornithological Society Conference, Oral presentation*, St. Petersburg, FL, 2013.

1. **Burnett, J.L.** and Sieving, K.E. Perceived predation risks of small forest birds. *Association of Field Ornithologists Annual Conference*, Poster presentation. Venus, FL, 2013.

## Invited Talks

1. Invited talk. Decline of the Once-Ubiquitous House Sparrow in North America. *Nebraska Invasive Species Council*, Lincoln, N.E., 2015.

1. Guest lecture. *Using Citizen Science Data in Avian Invasion Ecology*, in undergraduate course, *Ecology of Avian Invasions*, 2013. Interactive discussion and lecture on finding and utilizing open-sourced data online to understand the dynamics and ecology of avian invasions.

## Grants
####*for research*   
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IFAS Extension Internship for Undergraduate Research, University of Florida __$2,200__  
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ordway-Swisher Biological Station Undergraduate Research, University of Florida __$550__ 

####*for travel*   

2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nelson Memorial Fellowship, Univeristy of Nebraska-Lincoln __$695__  
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kellogg Biological Station, Michigan State University and Big Ten Academic Alliance __$500__  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Nelson Memorial Fellowship](http://newsroom.unl.edu/announce/snr/5519/31162), Univeristy of Nebraska-Lincoln __$900__  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Center for Great Plains Studies, Univeristy of Nebraska-Lincoln __$750__   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;American Ornithologists' Union __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NSF Diversity Award, Southeastern Ecology and Evolution Conference __$650__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graduate Student Council, University of Florida __$350__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of Research University of Florida __$500__  
2014&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of the Dean, Institute of Food and Agricultural Sciences, University of Florida __$750__  

####*for membership*

2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;American Ornithologists' Union Undergraduate Student Membership Award

## Honors & Awards
2017-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fling Fellowship, University of Nebraska-Lincoln  **$20,000**    
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Big Ten Academic Alliance Traveling Scholar  
2016-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;University of Nebraska Center for Great Plains Studies [Graduate Fellow](http://www.unl.edu/plains/graduate-fellows-program)       
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AAAS/Science Program for Excellence in Science Award     
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2<sup>nd</sup> place, School of Natural Resources Elevator Speech Competition **$300**   
2015-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Resilience Alliance Young Scholar (Invitation Only)  
2015-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Othmer Fellowship, University of Nebraska-Lincoln  **$24,000**     

## Relevant Skills 

**Quantitative ecological methods**     
&nbsp;&nbsp;&nbsp;&nbsp;-- Time series anlaysis      
&nbsp;&nbsp;&nbsp;&nbsp;-- Information theory   
&nbsp;&nbsp;&nbsp;&nbsp;-- Structural equation modeling    
&nbsp;&nbsp;&nbsp;&nbsp;-- Occupancy analyses    
&nbsp;&nbsp;&nbsp;&nbsp;-- Model based inference  
&nbsp;&nbsp;&nbsp;&nbsp;-- Utilizes both Bayesian and frequentist approaches  

**Statistical programs**  
&nbsp;&nbsp;&nbsp;&nbsp;-- Program R (advanced)  
&nbsp;&nbsp;&nbsp;&nbsp;-- SAS (intermediate)  
&nbsp;&nbsp;&nbsp;&nbsp;-- MatLab (novice)  

**Other**  
&nbsp;&nbsp;&nbsp;&nbsp;-- Data management and version control       
&nbsp;&nbsp;&nbsp;&nbsp;-- Local and remote research and writing collaborations     
&nbsp;&nbsp;&nbsp;&nbsp;-- Field and laboratory experimental design   
&nbsp;&nbsp;&nbsp;&nbsp;-- Familiar with IACUC    

## Recent Service
####*University of Nebraska-Lincoln*  
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Key player in achieving institutional membership to the Association for Women in Science](http://news.unl.edu/newsrooms/today/article/university-is-institutional-partner-with-association-for-women-in-science/)
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student Representative, [Faculty Advisory Committee](http://snr.unl.edu/employeeinfo/people/committee/facultyadvisory.asp), School of Natural Resources   
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student Representative, Digital Team, School of Natural Resources  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Organizer, Association for Women in Science [Mentor Workshop](http://snr.unl.edu/registration/AWISMentor/MentorMenteeRegistrationAttendanceCap.aspx?utm_source=Google&utm_medium=email&utm_term=&utm_content=&utm_campaign=AWIS+Workshop)   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Faculty Search Committee, [Urban and Community Forester](http://wfscjobs.tamu.edu/jobs/urban-and-community-forestry-professor-of-practice-university-of-nebraska-lincoln/)   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Seminar Coordinator](http://unlcms.unl.edu/snr/gsa/snr-gsa-seminar-coordinators), School of Natural Resources      
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founder & President, Natural Resources Diversity Initiative     
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department Representative Representative, Graduate Student Association   
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founder, Affiliate Chapter of the Association for Women in Science   

####*to the profession*    

2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Planning Committee for [Inclusive Ecology Section](http://www.esa.org/inclusive-ecology/), Ecological Society of America    
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reviewer, Wilson Journal of Ornithology    
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Liaison, [Urban Ecosystem Ecology Section](http://www.esa.org/urbanecology/),  Ecological Society of America   

## Societal Membership (since)
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Resilience Alliance   
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ecological Society of America   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Applied Ecology*, *Urban Ecosystem Ecology*, & *Student* sections  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wilson Ornithological Society 
