---
output: 
  pdf_document:
      latex_engine: pdflatex
      template: cv-latex.tex
  # md_document:
  #   variant: markdown_github
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding,
         output_format = "all") })
geometry: margin=.7in
title: "CV"
author: JESSICA L. BURNETT
orcid:  0000-0002-0896-5099
fontawesome: yes
email: jessicaleighburnett@gmail.com
github: trashbirdecology
twitter: trashbirdecol
phone: "+1 352 792 5425"
updated: yes
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---
<!-- *CV template adapted from* [S. Miller](https://github.com/svmiller/svm-r-markdown-templates) -->

<!-- [PDF version available](https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf) -->

# Education  

**Ph.D., Natural Resource Sciences, Specialization Applied Ecology** \hfill 2015 - 19  
School of Natural Resources, University of Nebraska-Lincoln, Nebrasaka USA

<!-- - Dissertation: Regime Detection Methods for the Practical Ecologist -->
<!-- - Prestigious funded summer research sabbatical at IIASA in Laxenburg, Austria  -->
<!-- - Recipient of 2 university-wide fellowships  and Meritorious Doctoral Student award  -->

**M.Sc., Wildlife Ecology & Conservation** \hfill 2013 - 15  
Department of Wildlife Ecology & Conservation, University of Florida, Florida USA

<!-- - Thesis: House Sparrow *(Passer domesticus)* decline and distribution in North America  -->

**B.Sc. Wildlife Ecology & Conservation** \hfill 2010 - 13  
Department of Wildlife Ecology & Conservation, University of Florida, Florida USA

<!-- - Undergraduate research thesis published (avian playback methodology) -->
<!-- - Internship with the Florida Wildlife Research Institute (GIS analyst) -->

<!-- **A.A. Valencia Community College** \hfill 2008 - 10   -->
<!-- # Education (BRIEF) -->

<!-- Ph.D. Natural Resource Sciences  Unviersity of Nebrsaka-Lincoln \hfill *expected* 2019     -->
<!-- M.Sc. Wildlife Ecology & Conservation, Unviersity of Florida \hfill 2015   -->
<!-- B.Sc. Wildlife Ecology & Conservation Unviersity of Florida \hfill 2013     -->
<!-- A.A. General studies Valencia Community College \hfill 2010   -->

# Skills Highlight
- Languages: R, LaTeX, MatLab, HTML, English
- Reproducibility and open science 
- Applied statistics
<!-- - Data quality assessment and quality control, data management -->
<!-- - Citizen science and long-term monitoring -->
- Avian community and population ecology
- Population trend and parameter estimation

# Professional Experience
**Research Ecologist & Mendenhall Postdoctoral Fellow**  \hfill September 2019 - present  
Science Analytics and Synthesis, Core Science Systems  
U.S. Geological Survey, Lakewood, Colorado, USA

**Graduate Research Assistant**   \hfill August 2015 - August 2019  
Nebraska Cooperative Fish & Wildlife Research Unit   
School of Natural Resources  
Department of Agronomy & Horticulture  
University of Nebraska-Lincoln, Nebraska, USA

<!-- - Published 8 peer-reviewed scientific articles and 1 invited book chapter -->
<!-- - Authored 5 R packages: -->
<!--     - [`bbsAssistant`](http://github.com/trashbirdecology/bbsAssistant): An R package containing helper functions for downloading and munging data and metadata from the North American Breeding Bird Survey FTP -->
<!--     - [`regimeDetectionMethods`](http://github.com/trashbirdecology/regimeDetectionMethods): An R package for calculating various regime detection measures -->
<!--     - [`bbsRDM`](http://github.com/trashbirdecology/bbsRDM): An R package for calculating various regime detection measures using the North American Breeding Bird Survey data -->
<!-- - Co-authored two R packages: -->
<!--     - [`radsets`](https://github.com/natbprice/radsets): An R package for interactive, network-based visualizations of overlapping sets -->
<!--     - [`TVdiff`](https://github.com/natbprice/tvdiff): An R package for implementing numerical differentiation of noisy, non-smooth data -->
<!-- - Designed and instructed of workshops for managing and analyzing ecological data using Program R -->
<!-- - Co-organizer of half-day research symposium at national conference (North American Ornithological Conference) -->
<!-- - Co-creator of the University's Association for Women in Science and the Natural Resources Diversity Initiative -->
<!-- - Invited and hosted three departmental seminar guests -->
<!-- - Invited talk at the Association for Women in Math Biology annual symposium -->

**Young Scholar**    \hfill May 2018 - September 2018  
Applied Systems Analysis Research Group  
International Institute for Applied Systems Analysis 
Laxenburg, Austria

<!-- - Research sabbatical advised by applied mathematician (E. Rovenskaya) and systems ecologist (B. Fath) -->
<!-- - Presented research in an international forum -->
<!-- - Organized seminar on Network Analysis in Ecology -->

**Graduate Teaching Assistant**   \hfill August 2013 - August 2015   
Department of Wildlife Ecology & Conservation  
University of Florida, Florida, USA

<!-- - Published 2 peer-reviewed scientific articles -->
<!-- - Invited lectures in citizen science data, wetland birds -->

**Geospatial Analyst Intern**  \hfill April 2012 -  August 2012  
Florida Fish and Wildlife Research Institute
Gainesville, Florida, USA

<!-- - Identified relationships among land cover and American Kestrel *(Falco sparverius)* nest success -->
<!-- - Ground-truthed GIS data -->
<!-- - Monitored Eastern Screech-Owl (*Megascops asio*) nests -->

**Research Assistant**  \hfill January 2011 -  April 2012  
Avian Ecology and Conservation Lab
University of Florida, Gainesville, FL, USA

<!-- - Managed bird banding database -->
<!-- - Conducted avian behavioral field research - *Paridae* feeder behavior -->
<!-- - Designed and implemented research project resulting in 1 peer-reviewed manuscript -->

**Crew Leader, Smithsonian Fellow**  \hfill   April-September 2011 and April-September 2013  
Neighborhood Nestwatch Program  
Smithsonian Migratory Bird Center, Gainesville, FL, USA

<!-- - Trained and led team of banding technicians -->
<!-- - Managed bird banding database; data QA/QC -->
<!-- - Recruited and trained citizen scientists -->
<!-- - Banded and measured breeding birds in backyards using -->
<!-- - Created monthly program newletters -->


# Publications 
1. **Burnett, J.L.**, L.S. Wszola, and G. Palomo-Munoz. 2019. bbsAssistant: An R package for downloading and handling data and information from the North American Breeding Bird Survey. Journal of Open Source Software, 4(44), 1768, DOI: [10.21105/joss.01768](https://doi.org/10.21105/joss.01768)

1. Donovan, V.M., **J.L. Burnett**, C.H. Bielski, H.E. Birge, R. Bevans, D. Twidwell, and C.R. Allen. 2018. Social-ecological landscape patterns predict woody encroachment from native tree plantings in a temperate grassland *Ecology and Evolution* 8(19): 9624-9632 DOI:10.1002/ece3.4340

1.  **Burnett, J.L.**, K.L. Pope, A. Wong, C.R. Allen, D.M. Haak, B.J. Stephen, and D.R. Uden. 2018. Thermal tolerance limits of the invasive Chinese mysterysnail *Bellamya chinensis* and implications for management". *American Malacological Bulletin* 36(1): 140-144 DOI:10.4003/006.036.0106   

1. Roberts, C.P., D. Twidwell, **J.L. Burnett**, V.M. Donovan, C. Wonkka, C.H. Bielski, A.S. Garmestani, D.G. Angeler, T. Eason, B.W. Allred, M.O. Jones, D.E. Naugle, S. Sundstrom, C.R. Allen . 2018. Early warnings for state transitions. *Rangeland Ecology and Management* DOI:10.1016/j.rama.2018.04.012     

1. La Sorte, F.A., C.A. Lepczyk, **J.L. Burnett**, A. Hurlbert, M. Tingley, and B. Zuckerberg. 2018. Opportunities and challenges for big data ornithology. *The Condor* 120(2): 414-426 DOI:0.1650/CONDOR-17-206.1

1. Chuang, W.C., A.S. Garmestani, T. Eason, T.L. Spanbauer, H.B. Fried-Peterson, C. Roberts, S. Sundstrom, **J.L. Burnett**, D. G. Angeler, B. Chaffin, L. Gunderson, D. Twidwell, C.R. Allen. 2018. Enhancing quantitative approaches for assessing ecological and community resilience. *Journal of Environmental Management* 213: 353-362 DOI:10.1016/j.jenvman.2018.01.083    

1.  **Burnett, J.L.**, C.R. Allen, C.P. Roberts, M.Bomberger Brown, and M.P. Moulton. 2017. Eurasian Tree Sparrow (*Passer montanus*) range expansion in North America. *Biological Invasions* 19(1): 5-9 DOI:10.1007/s10530-016-1273-4  

1.  **Burnett, J.L.** and K.E. Sieving. 2016. Songbird distress call as a detection enhancement method and application to Red-shouldered Hawks (*Buteo lineatus*). *Florida Field Naturalist* 44(4):157-168      

1. C.R. Allen, H.E. Birge, S.L. Bartlet-Hunt, R.A. Bevans, **J.L. Burnett**, B.A. Cosens, X. Cai, A.S. Garmestani, I. Linkov, E.A. Scott, M.D. Solomon, and D.R. Uden. 2016. Avoiding decline: Fostering resilience and sustainability in midsize cities. *Sustainability* 8(9):844-868 DOI:10.3390/su8090844   

1. **Burnett, J.L.** and M.P. Moulton. 2015. Recent trends in House Sparrow (*Passer domesticus*) distribution and abundance in Gainesville, Alachua County, Florida. *Florida Field Naturalist* 43(4):167-172   

# Book Chapters
1. **Burnett, J.L.** and C.R. Allen (2020) Continental Analysis of Invasive Birds:  North America *in* Downs, C.T. and Hart, L.A. (eds) Global trends and impacts of alien invasive birds. CABI, Wallingford, U.K., pp. XX-XX. 

# Manuscripts Under Review (primary author)  
1. **Burnett, J.L.**, N.B. Price, A.J. Tyre,  D.G. Angeler, T. Eason, D. Twidwell., and C.R. Allen. Deconstructing the steps for calculating Fisher Information as a measure of abrupt change in ecological systems. *under review at Ecological Modelling*

1. **Burnett, J.L.**, R. Wilcox, B. Stephen, D. Haak, D. Uden, C.R. Allen, and K. Pope. Shell strength does not limit predation of an invasive snail species (Bellamya chinensis) by native fish. *under review at Malacological Bulletin*

# Manuscripts in Preparation (primary author) 
1. **Burnett, J.L.**, Kratter, A. and Robinson, S.K. Using a Christmas Bird Count to understand local and regional changes in bird populations in Northcentral Florida. 

1. **Burnett, J.L.**, N.B. Price, C.R. Allen, D. Twidwell, A.J. Tyre. Velocity of distance travelled as a measure of ecosystem trajectory and abrupt change. 

1. **Burnett, J.L.**, Z. Warren, M. Podebrovska, B. Dueker, K. Lamke, B. Seguin, D. Twidwell, and C.R. Allen. Sexual size dimorphism in mammalian communities of Mediterranean Australian regions.

1. **Burnett, J.L.**, L. Wszola, N. Mirochnitchenko, E. Stuber, M. Bomberger Brown, C.R. Allen, D. Twidwell, and J. Carroll. Large-scale crop patterns influence Gray Partridge (*Perdix perdix*) site occupancy in North America. 

1. **Burnett, J.L.**, B.D. Fath, E. Rovenskaya, and A.J. Tyre. Effects of data quality and quantity on inference gained from regime shift detection methods. 


# Software
## Author and maintainer
1. **Burnett, J.L.**, L.S. Wszola, and G. Palomo-Munoz. 2019. `bbsAssistant`: An R package for downloading and handling data and information from the North American Breeding Bird Survey: U.S. Geological Survey software release. DOI: [10.5066/P93W0EAW](https://doi.org/10.5066/P93W0EAW).  [GitHub repository](https://github.com/TrashBirdEcology/bbsAssistant).

1. **Burnett, J.L.**, N.B. Price. 2019. `regimeDetectionMeasures`. An R package for calculating univariate and multivariate regime detection methods using community time series.  [Github:trashbirdecology/regimedetectionmeasures](https://github.com/TrashBirdEcology/regimedetectionmeasures)
1. **Burnett, J.L.**, N.B. Price, and A.J. Tyre. 2018. `distanceTravelled`. An R package for calculating the distance traveled by a multispecies community along a time series. [Github:trashbirdecology/distancetravelled](https://github.com/TrashBirdEcology/distancetravelled)

## Author
1. Price, N.B. and **J.L. Burnett**. `tvdiff`. 2019.  An R package for numerical differentiation of noisy, non-smooth data. [Github:natbprice/tvdiff](https://github.com/natbprice/tvdiff) 
1. Price, N.B., C. Chizinski, and **J.L. Burnett**. `radsets`. 2019. An R package for interactive, network-based visualizations of overlapping sets.  [Github:natbprice/radsets](https://natbprice.github.io/radsets/)

# Grants in Review
- Integrating Two Foundational USGS Data Products: the Breeding Bird Survey (BBS) and the Bird Banding Lab (BBL) Data, Community for Data Integration, U.S. Geological Survey \hfill in review

# Grants & Fellowships  
- Co-PI, CIEE/ICEE Working Group: Creating a unified approach to evaluate regime shift detection methods,  __$12,400 CA__\hfill 2020
- Mendenhall Postdoctoral Fellowship, U.S. Geological Survey __~$222,000__ \hfill 2019 - 21
- [Meritorious Graduate Student](http://snr.unl.edu/aboutus/what/awardscomplete.asp), School of Natural Resources, UNL __$500__ \hfill 2018
- Participant, [Research Collaboration Workshop for Women in Mathematical Biology, NIMBIOS](http://www.nimbios.org/education/WS_wwmb)  \hfill 2018
- Fling Fellow, University of Nebraska-Lincoln  **$20,000** \hfill 2016 - 17 
- Othmer Fellow, University of Nebraska-Lincoln  **$24,000** \hfill 2015 - 19 
- Big Ten Academic Alliance Travelling Scholar \hfill 2017
- AAAS/Science Program for Excellence in Science Award \hfill 2016
- Graduate Fellow, Center for Great Plains Studies, University of Nebraska \hfill 2016 - 18 
- 2<sup>nd</sup> place, School of Natural Resources Elevator Speech Competition **$300** \hfill 2016
- Resilience Alliance Young Scholar, The Resilience Alliance \hfill 2015 - 17 


# Honors & Awards 
- School of Natural Resources, University of Nebraska-Lincoln __$750__     \hfill 2019
- University of Nebraska Graduate Travel Fund __$750__ \hfill 2019
- Association for Women in Mathematical Biology __$650__ \hfill 2019
- School of Natural Resources, University of Nebraska-Lincoln __$1050__     \hfill 2019
- National Academy of Sciences research award __$5,500__ \hfill 2018
- National Science Foundation & NimBios __$550__   \hfill 2018
- Kellogg Biological Station, Michigan State University __$500__   \hfill 2017
- Nelson Memorial Fellowship, University of Nebraska-Lincoln __$3,217__ *(3x recipient)*   \hfill 2016 - 18
- Center for Great Plains Studies, University of Nebraska-Lincoln __$3,000__ *(4x recipient)*    \hfill 2015 - 18 
- American Ornithologists' Union **$250**  \hfill 2016
- NSF Diversity Award, Southeastern Ecology and Evolution Conference __$650__   \hfill 2015
- Graduate Student Council, University of Florida __$350__    \hfill 2015
- Office of Research, University of Florida __$500__     \hfill 2015
- Department of Wildlife Ecology & Conservation, University of Florida __$500__ *(2x recipient)*   \hfill 2014 - 15
- Office of the Dean, Institute of Food and Agricultural Sciences, University of Florida __$750__   \hfill 2013
- American Ornithologists' Union Undergraduate Student Membership Award \hfill 2013
- IFAS Extension Internship for Undergraduate Research, University of Florida __$2,200__  \hfill  2013
- Ordway-Swisher Biological Station Undergraduate Research Grant, University of Florida __$550__   \hfill  2013

# Teaching Experience  

**Co-instructor** Introduction to Applied Ecological Statistics, Kearney, NE \hfill 2017
<!-- - Week-long workshop for employees of the Nebraska Game and Parks Commission employees -->

**Instructor** Introduction to Prorgam R \hfill 2017
<!-- - Designed and taught a series of half-day workshops for graduate students -->
<!-- - Basics of data management and analysis using Program R -->

**Guest Lecturer** Module: using citizen science data to understand ecological invasions; Course: Avian Invasions  \hfill 2016
<!-- - Designed and taught series of lectures on citizen science data     -->

**Teaching Assistant** Wildlife Population Ecology, Department of Wildlife Ecology & Conservation, University of Florida \hfill 2015
<!-- - Lead quantitative laboratory sessions, grading   -->

**Teaching Assistant** Ecological Statistics, Department of Wildlife Ecology & Conservation, University of Florida \hfill 2015
<!-- - Lead and moderate discussions, grading   -->

**Guest Lecturer** Wetland birds module, Florida Master Naturalist \hfill 2013
<!-- - Designed and taught module on wetland bird identification and ecology   -->

# Organized Sessions & Symposia
1. Using the integrated modelling framework to bridge science and decision making: advances, applications, and opportunities. Co-organizer wtih J.A. Royle. Ecological Society of America conference,s __in review__
1. Opportunities and Challenges in Big Data Ornithology. Co-organizer with F. LaSorte and C. Lepczyk. North American Ornithological Conference V, Washington, D.C., 2016

# Research Presentations Given
## invited

1. Regime Detection Measures for the Pratical Ecologist, Department of Wildlife Ecology & Conservation, University of Florida, 2019

1. Detecting abrupt change in bird community time series using distance travelled. *Association for Women in Math Biology Symposium*, Special session "Current Challenges in Mathematical Biology ", Houston, TX, 2019

1. Decline of the Once-Ubiquitous House Sparrow in North America. *Nebraska Invasive Species Council*, Lincoln, NE, 2015     

## contributed
1. **Burnett, J.L.**, N.B. Price, and A.J. Tyre. A novel method for tracking ecosystem trajectory and abrupt change in space-time: distance traveled. *International Association for Landscape Ecology*, Oral presentation. Fort Collins, CO, 2019

1. **Burnett, J.L.**, R. Crystal-Ornelas, D. Fogarty, K. Hogan, C.R. Allen, M. Bomberger Brown, D. Twidwell, and C.A. Lepczyk. Impacts of non-native birds on native wildlife in urban ecosystems: where is the evidence?  *Natural Areas Conference*, Oral presentation. Indiana, 2018

1. **Burnett, J.L.**. Advances in ecological regime shift detection, *International Institute for Applied Systems Analysis*, Oral presentation. Laxenburg, Austria, 2018

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. Community velocity as a regime shift detection method. *Great Plains Grassland Summit*, Poster presentation. Denver, Colorado, 2018

1. **Burnett, J.L.**, L. Wszola, N. Mirochnitchenko, E. Stuber, M. Bomberger Brown, C.R. Allen, D. Twidwell, and J.P. Carroll.  Gray partridge distribution in North America: Changing landscapes and environment for an introduced species. Perdix XIV and IUGB, Oral presentation by JPC, Montpellier,
France, 2017

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. System trajectory and Fisher information as early-warning indicators of ecological regime shifts. *Resilience 2017: Resilience Frontiers for Global Sustainability*, Poster presentation. Stockholm, Sweden, 2017

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. System trajectory and Fisher information as early-warning indicators of ecological regime shifts. *Ecological Society of America*, Poster presentation. Portland, OR, 2017

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Ecological Regime Shifts in the Central Great Plains. *Great Plains Symposium*, Oral presentation. Nebraska Innovation Campus, Lincoln, NE, 2017

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Using Big Data to Detect Regime Shifts in Space and Time. *North American Ornithological Conference VI*, Poster presentation. Smithsonian Migratory Bird Institute, Washington, D.C., 2016

1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? Southeastern Ecology and Evolution Conference, Oral presentation. University of Georgia, Athens, GA, 2015  

1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M.L., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? *American Ornithologists' Union and Cooper Ornithological Society Annual Meeting*, Poster presentation. Norman, OK, 2015  

1. **Burnett, J.L.**, Moulton, M.P., and Sieving, K.E. House sparrow: the decline of a once ubiquitous, invasive species. *Florida Chapter of The Wildlife Society Annual Conference*, Poster presentation. Safety Harbor, FL, 2014.

1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M.L., and Robinson, S.K. House Sparrow decline and distribution in North Central Florida. *Florida Cooperative Fish and Wildlife Research Unit annual cooperators meeting*, Poster presentation. Gainesville, FL, 2014  

1. **Burnett, J.L.** and Sieving, K.E. Detecting birds of prey using tufted titmouse distress calls. *USGS Florida Cooperative Fish and Wildlife Research Unit Committee Meeting*, Poster presentation. Gainesville, FL, 2013

1. **Burnett, J.L.** and Sieving, K.E. Do actual and perceived risks of small forest birds align? *Florida Ornithological Society Conference, Oral presentation*, St. Petersburg, FL, 2013

1. **Burnett, J.L.** and Sieving, K.E. Perceived predation risks of small forest birds. *Association of Field Ornithologists Annual Conference*, Poster presentation. Venus, FL, 2013


# Scientific Outreach 
## Community Involvement
- Letters to a Pre-scientist, United States, 2019-present
- Skype a Scientist, United States, 2017-present
- Co-PI, Community grant to develop on-site nature trail and viewing opportunities at the Reichert House, Gainesville, FL, 2014-15
- Hands-on captive herpetological opportunities for studnets of the Reichert House, Gainesville, FL, 2014-15 
- Birdwatching and live banding demonstrations for K-12 students, A Girls' Place, Gainesville, FL, 2013-15
- Science, mathematics and reading tutor for middle and high school students, Friends of the Micanopy Library, FL, 2011-13 
- Learning assistant and tutor for geometry and pre-calculus students, Valencia Community College, Oralndo, FL 2008-2010 

## Blogs  
- [Connecting to nature and understanding ecosystem services: urban perspective](https://envirobites.org/2017/10/17/connecting-to-nature-and-understanding-ecosystem-services-the-urban-perspective/), Envirobites
- [Big data, big problems](http://resilience2017.org/blog/big-data-big-problems/), Resilience Alliance 
- [Panarchy in the Anthropocene](http://resilience2017.org/blog/panarchy-in-the-anthropocene/), Resilience Alliance - [Regime shifts, traps and how to deal with them](http://resilience2017.org/blog/regime-shifts-traps-and-how-to-deal-with-them/), Resilience Alliance
- [Connecting to nature and understanding ecosystem services: the urban perspective](http://resilience2017.org/blog/connecting-to-nature-and-understanding-ecosystem-services-the-urban-perspective/), Resilience Alliance
- [Leadership resilience and your workplace](http://resilience2017.org/blog/leadership-resilience-and-your-workplace/), Resilience Alliance

## Radio
- [House Sparrow declines in North American, Urban Wildlife Podcast](http://www.urbanwildlifecast.com/?p=139)   

# Service  
## Journal Referee
- *Bioinvasions Records* (1), *Ecological Modelling* (4), *Journal of Molluscan Studies* (2), *Journal of Open Source Software* (1), *PLOS One* (1), *Wilson Journal of Ornithology* (3)  
- Student liaison, [Urban Ecosystem Ecology Section](http://www.esa.org/urbanecology/), Ecological Society of America \hfill 2015 - 16  

## University of Nebraska-Lincoln 
- Co-founder, Natural Resources Diversity Initiative committee, School of Natural Resources \hfill 2017
- Co-founder, [Institutional membership to the Association for Women in Science](http://news.unl.edu/newsrooms/today/article/university-is-institutional-partner-with-association-for-women-in-science/) \hfill 2016
- [Faculty Advisory Committee](http://snr.unl.edu/employeeinfo/people/committee/facultyadvisory.asp), School of Natural Resources \hfill 2016-18 
- Digital Team, School of Natural Resources \hfill 2016
- Organizer, Association for Women in Science [Mentor Workshop](http://snr.unl.edu/registration/AWISMentor/MentorMenteeRegistrationAttendanceCap.aspx?utm_source=Google&utm_medium=email&utm_term=&utm_content=&utm_campaign=AWIS+Workshop) \hfill 2016
- [Seminar](http://unlcms.unl.edu/snr/gsa/snr-gsa-seminar-coordinators) Coordinator, School of Natural Resources  \hfill 2016
- Department Representative, UNL Graduate Student Association  \hfill 2015 - 16

<!-- # Professional Memberships (since)    -->
<!-- - Association for Women in Mathematics  \hfill 2018 -->
<!-- - Resilience Alliance     \hfill 2015 -->
<!-- - Wilson Ornithological Society  \hfill 2015  -->
<!-- - Association for Women in Science \hfill 2015 -->
<!-- - Ecological Society of America   \hfill 2014 -->

# Grey Literature  
## White Papers
1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D. 2017. White Paper: Regime Shift Detection Using Fisher Information. Strategic Environmental Research and Development Program (SERDP RC 25-10), Department of Defense.  

## Grant Reports
1. Allen, C.R., Angeler, D.G., Twidwell, D., **Burnett, J.L.**, Roberts, C.P. 2017. Interim Report (RC 25-10): Global Change, Vulnerability, and Resilience: Management Options for an Uncertain Future. Strategic Environmental Research and Development Program (SERDP), Department of Defense.   
1. Twidwell D., Bielski, C.H., **Burnett, J.L.**, Donovan, V.M., Wonkka, C.L. 2017. Review of LANDFIRE Biophysical Settings Models (BpS) in the Great Plains. LANDFIRE Project.   