---
output:
  pdf_document: "default"
---

#Jessica L. Burnett  
### [Computational Ecology](https://armchairecology.blog/two-schools-ecology/) | Macroecology | Regime Shifts

<!-- **I am Schedule A eligible and wish to be considered under Schedule A hiring authority if applicable.** -->


## Education  
<!-- 2019&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ph.D., Natural Resource Sciences and Applied Ecology, University of Nebraska-Lincoln      -->
<!-- 2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M.Sc., Wildlife Ecology and Conservation, University of Florida   -->
<!-- 2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B.Sc., Wildlife Ecology and Conservation, University of Florida   -->
<!-- 2010&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A.A., Valencia Community College   -->

2019 *expected* &nbsp;&nbsp;&nbsp;Ph.D., Natural Resource Sciences and Applied Ecology, University of Nebraska-Lincoln     
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M.Sc., Wildlife Ecology and Conservation, University of Florida  
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B.Sc., Wildlife Ecology and Conservation, University of Florida  
2010&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A.A., Valencia Community College  



## Professional Appointments  
2015-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graduate Research Assistant, University of Nebraska-Lincoln     
2013-15&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graduate Teaching and Research Assistant, University of Florida  
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Geospatial Analyst, Florida Fish and Wildlife Research Institute    
2011-13&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Research Assistant, Sieving Lab of Avian Ecology and Conservation, University of Florida   
2011-13&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Smithsonian Fellow, Neighborhood Nestwatch Crew Leader, Smithsonian Migratory Bird Center  


<!-- **Front of House Manager** (2008-2010)    -->
<!-- Bakely's Restaurant | Winter Park, Florida -->

<!-- **Sales and Catering Assistant Manager** (2006-2007)     -->
<!-- Clarion Hotel Downtown | Raleigh, North Carolina -->

<!-- **Front Desk Manager** (2005-2006)     -->
<!-- Clarion Hotel Downtown | Raleigh, North Carolina -->

# Peer-reviewed publications  

1.  **Burnett, J.L.**, K.L. Pope, A. Wong, C.R. Allen, D.M. Haak, B.J. Stephen, and D.R. Uden. 2018. Thermal tolerance limits of the invasive Chinese mysterysnail *Bellamya chinensis* and implications for management". *American Malacological Bulletin* 36(1): 140-144 DOI:10.4003/006.036.0106   

1. Donovan, V.M., **J.L. Burnett**, C.H. Bielski, H.E. Birge, R. Bevans, D. Twidwell, and C.R. Allen. (2018) Social-ecological landscape patterns predict woody encroachment from native tree plantings in a temperate grassland *Ecology and Evolution* 8(19): 9624-9632 DOI:10.1002/ece3.4340

1. La Sorte, F.A., C.A. Lepczyk, **J.L. Burnett**, A. Hurlbert, M. Tingley, and B. Zuckerberg. 2018. Opportunites and challenges for big data ornithology. *The Condor* 120(2): 414-426 DOI:0.1650/CONDOR-17-206.1

1. Roberts, C.P., D. Twidwell, **J.L. Burnett**, V.M. Donovan, C. Wonkka, C.H. Bielski, A.S. Garmestani, D.G. Angeler, T. Eason, B.W. Allred, M.O. Jones, D.E. Naugle, S. Sundstrom, C.R. Allen,  (2018) Early warnings for state transitions. *Rangeland Ecology and Management* DOI:10.1016/j.rama.2018.04.012   

1. Chuang, W.C., A.S. Garmestani, T. Eason, T.L. Spanbauer, H.B. Fried-Peterson, C. Roberts, S. Sundstrom, **J.L. Burnett**, D. G. Angeler, B. Chaffin, L. Gunderson, D. Twidwell, C.R. Allen. 2018. Enhancing quantitative approaches for assessing ecological and community resilience. *Journal of Environmental Management* 213: 353-362 DOI:10.1016/j.jenvman.2018.01.083    

1.  **Burnett, J.L.**, C.R. Allen, C.P. Roberts, M.Bomberger Brown, and M.P. Moulton. 2017. Eurasian Tree Sparrow (*Passer montanus*) range expansion in North America. *Biological Invasions* 19(1): 5-9 DOI:10.1007/s10530-016-1273-4  

1.  **Burnett, J.L.** and K.E. Sieving. 2016. Songbird distress call as a detection enhancement method and application to Red-shouldered Hawks (*Buteo lineatus*). *Florida Field Naturalist* 44(4):157-168      

1. C.R. Allen, H.E. Birge, S.L. Bartlet-Hunt, R.A. Bevans, **J.L. Burnett**, B.A. Cosens, X. Cai, A.S. Garmestani, I. Linkov, E.A. Scott, M.D. Solomon, and D.R. Uden. 2016. Avoiding decline: Fostering resilience and sustainability in midsize cities. *Sustainability* 8(9):844-868 DOI:10.3390/su8090844   

1. **Burnett, J.L.** and M.P. Moulton. 2015. Recent trends in House Sparrow (*Passer domesticus*) distribution and abundance in Gainesville, Alachua County, Florida. *Florida Field Naturalist* 43(4):167-172   

# First-authored manuscripts under review  
1. **Burnett, J.L.**, R. Wilcox, B. Stephen, D. Haak, D. Uden, C.R. Allen, and K. Pope. Shell strength does not limit predation of an invasive snail species (Bellamya chinensis) by native fish. *under review at Journal of Freshwater Ecology*

# First-authored manuscripts in preparation (available upon request)  
1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, T. Eason, C.R. Allen, and D. Twidwell. A guide to Fisher Information for ecologists.

1. **Burnett, J.L.**, N.B. Price, C.R. Allen, B.D. Fath, E. Rovenskaya, D. Twidwell, A.J. Tyre, P. Zebrowski. Distance travelled: using Pythagorean's theorem to track ecosystem tracjectory and abrupt change. 

1. **Burnett, J.L.**, Z. Warren, M. Podebrovska, B. Dueker, K. Lamke, B. Seguin, D. Twidwell, and C.R. Allen. Sexual size dimorphism in mammalian communities of mediterranean Australian regions.

1. **Burnett, J.L.**, L. Wszola, N. Mirochnitchenko, E. Stuber, M. Bomberger Brown, C.R. Allen, D. Twidwell, and J. Carroll. Large-sacle crop patterns influence Gray Partridge (*Perdix perdix*) site occupancy in North America. 

## Select Honors & Awards   
2017-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fling Fellowship, University of Nebraska-Lincoln  **$20,000**    
2016-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;University of Nebraska Center for Great Plains Studies [Graduate Fellow](http://www.unl.edu/plains/graduate-fellows-program)       
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AAAS/Science Program for Excellence in Science Award
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2<sup>nd</sup> place, School of Natural Resources Elevator Speech Competition **$300**   
2016-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Resilience Alliance Young Scholar, The Resilience Alliance   
2015-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Othmer Fellowship, University of Nebraska-Lincoln  **$24,000**     

## Grants
####*for research*   
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IFAS Extension Internship for Undergraduate Research, University of Florida __$2,200__  
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ordway-Swisher Biological Station Undergraduate Research, University of Florida __$550__ 

####*for travel*   
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nelson Memorial Fellowship, Univeristy of Nebraska-Lincoln __$695__  
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kellogg Biological Station, Michigan State University and Big Ten Academic Alliance __$500__  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Nelson Memorial Fellowship](http://newsroom.unl.edu/announce/snr/5519/31162), Univeristy of Nebraska-Lincoln __$900__  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Center for Great Plains Studies, Univeristy of Nebraska-Lincoln __$750__   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;American Ornithologists' Union __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NSF Diversity Award, Southeastern Ecology and Evolution Conference __$650__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graduate Student Council, University of Florida __$350__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of Research University of Florida __$500__  
2014&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of the Dean, Institute of Food and Agricultural Sciences, University of Florida __$750__  

####*for community outreach*
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outdoor Education Program, Reichert House, Gainesville Police Department, FL __$1,200__

## Recent Service
####*at the University of Nebraska-Lincoln*  
2018-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Natural Resources Diversity Initiative committee, University of Nebraska-Lincoln  
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Key player in achieving institutional membership to the Association for Women in Science](http://news.unl.edu/newsrooms/today/article/university-is-institutional-partner-with-association-for-women-in-science/)
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student Representative, [Faculty Advisory Committee](http://snr.unl.edu/employeeinfo/people/committee/facultyadvisory.asp), School of Natural Resources   
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student Representative, Digital Team, School of Natural Resources  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Organizer, Association for Women in Science [Mentor Workshop](http://snr.unl.edu/registration/AWISMentor/MentorMenteeRegistrationAttendanceCap.aspx?utm_source=Google&utm_medium=email&utm_term=&utm_content=&utm_campaign=AWIS+Workshop)   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Seminar Coordinator](http://unlcms.unl.edu/snr/gsa/snr-gsa-seminar-coordinators), School of Natural Resources      
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founder & President, Natural Resources Diversity Initiative student group     
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department Representative Representative, Graduate Student Association   
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founder, Affiliate Chapter of the Association for Women in Science   

####*to the profession*    
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Contributor to founding documents, Committee for [Inclusive Ecology Section](http://www.esa.org/inclusive-ecology/), ESA  
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reviewer, Wilson Journal of Ornithology    
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Liaison, [Urban Ecosystem Ecology Section](http://www.esa.org/urbanecology/), ESA

<!-- ## Societal Memberships (since) -->
<!-- 2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Resilience Alliance -->
<!-- 2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ecological Society of America -->
<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Applied Ecology*, *Urban Ecosystem Ecology*, & *Student* sections -->
<!-- 2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wilson Ornithological Society -->

## Grants & Fellowships Submitted (since 2016)
1. Principal investigator and author. [USGS Powell Center Synthesis Working Group](https://powellcenter.usgs.gov/) , "Scale mismatches in ecological research and management: consequences and solutions through data management." Co-PIs: Hao Ye, Craig R. Allen, George Sugihara. Not funded.

1. [Young Scientists Summer Program](http://www.iiasa.ac.at/web/home/education/yssp/about.html), International Institute for Applied Systems Analysis. Funded. 

1. [Mozilla Science Fellowship](https://science.mozilla.org/programs/fellowships/). 2016. Not funded.

## Teaching Experience  
**Co-instructor** \hfill 2017  

*Introduction to Applied Ecological Statistics, Kearney, NE*

- Week-long workshop for employees of the Nebraska Game and Parks Commission employees

**Instructor** \hfill 2017  
*Introduction to Prorgam R*

- Designed and taught a series of half-day workshops for graduate students
- Basics of data management and analysis using Program R

**Guest Lecturer** \hfill 2016  
*Module: using citizen science data to understand ecological invasions; Course: Avian Invasions*

- Designed and taught series of lectures on citizen science data    

**Teaching Assistant** \hfill 2015   

*Wildlife Population Ecology, Department of Wildlife Ecology & Conservation, University of Florida*

- Lead quantitative laboratory sessions, grading  

**Teaching Assistant** \hfill 2015   

*Ecological Statistics (online-only course), Department of Wildlife Ecology & Conservation, University of Florida*

- Lead and moderate discussions, grading  

**Guest Lecturer** \hfill 2013  
*Wetland birds module, Florida Master Naturalist*

- Designed and taught lecture on wetland bird identification and ecology  

## Agency Reports  

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D. 2017. White Paper: Regime Shift Detection Using Fisher Information. Strategic Environmental Research and Development Program (SERDP), Department of Defense.  

1. Allen, C.R., Angeler, D.G., Twidwell, D., **Burnett, J.L.**, Roberts, C.P. 2017. Interim Report (RC 25-10): Global Change, Vulnerability, and Resilience: Management Options for an Uncertain Future. Strategic Environmental Research and Development Program (SERDP), Department of Defense.  

1. Twidwell D., Bielski, C.H., **Burnett, J.L.**, Donovan, V.M., Wonkka, C.L. 2017. Review of LANDFIRE Biophysical Settings Models (BpS) in the Great Plains. LANDFIRE Project. 

## Presentations

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. System trajectory and Fisher information as early-warning indicators of ecological regime shifts. *Resilience 2017: Resilience Frontiers for Global Sustainability*, Poster presentation. Stockholm, Sweden, 2017

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. System trajectory and Fisher information as early-warning indicators of ecological regime shifts. *Ecological Society of America*, Poster presentation. Portland, OR, 2017

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Ecological Regime Shifts in the Central Great Plains. *Great Plains Symposium*, Oral presentation. Nebraska Innovation Campus, Lincoln, NE, 2017.

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Using Big Data to Detect Regime Shifts in Space and Time. *North American Ornithological Conference VI*, Poster presentation. Smithsonian Migratory Bird Institute, Washington, D.C., 2016

1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? Southeastern Ecology and Evolution Conference, Oral presentation. University of Georgia, Athens, GA, 2015  

1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M.L., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? *American Ornithologists' Union and Cooper Ornithological Society Annual Meeting*, Poster presentation. Norman, OK, 2015.  

1. **Burnett, J.L.**, Moulton, M.P., and Sieving, K.E. House sparrow: the decline of a once ubiquitous, invasive species. *Florida Chapter of The Wildlife Society Annual Conference*, Poster presentation. Safety Harbor, FL, 2014.

1. **Burnett, J.L.** and Sieving, K.E. Detecting birds of prey using tufted titmouse distress calls. *USGS Florida Cooperative Fish and Wildlife Research Unit Committee Meeting*, Poster presentation. Gainesville, FL, 2013.

1. **Burnett, J.L.** and Sieving, K.E. Do actual and perceived risks of small forest birds align? *Florida Ornithological Society Conference, Oral presentation*, St. Petersburg, FL, 2013.

1. **Burnett, J.L.** and Sieving, K.E. Perceived predation risks of small forest birds. *Association of Field Ornithologists Annual Conference*, Poster presentation. Venus, FL, 2013.

## Invited Talks

1. Invited talk. Decline of the Once-Ubiquitous House Sparrow in North America. *Nebraska Invasive Species Council*, Lincoln, N.E., 2015.

1. Guest lecture. *Using Citizen Science Data in Avian Invasion Ecology*, in undergraduate course, *Ecology of Avian Invasions*, 2013. Interactive discussion and lecture on finding and utilizing open-sourced data online to understand the dynamics and ecology of avian invasions.

## Grants
####*for research*   
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IFAS Extension Internship for Undergraduate Research, University of Florida __$2,200__  
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ordway-Swisher Biological Station Undergraduate Research, University of Florida __$550__ 

####*for travel*   
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nelson Memorial Fellowship, Univeristy of Nebraska-Lincoln __$695__  
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kellogg Biological Station, Michigan State University and Big Ten Academic Alliance __$500__  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Nelson Memorial Fellowship](http://newsroom.unl.edu/announce/snr/5519/31162), Univeristy of Nebraska-Lincoln __$900__  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Center for Great Plains Studies, Univeristy of Nebraska-Lincoln __$750__   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;American Ornithologists' Union __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NSF Diversity Award, Southeastern Ecology and Evolution Conference __$650__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graduate Student Council, University of Florida __$350__  
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of Research University of Florida __$500__  
2014&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department of Wildlife Ecology and Conservation, University of Florida __$250__    
2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office of the Dean, Institute of Food and Agricultural Sciences, University of Florida __$750__  

####*for membership*

2013&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;American Ornithologists' Union Undergraduate Student Membership Award

## Honors & Awards   
2017-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fling Fellowship, University of Nebraska-Lincoln  **$20,000**      
2017-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Big Ten Academic Alliance Traveling Scholar  
2016-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;University of Nebraska Center for Great Plains Studies [Graduate Fellow](http://www.unl.edu/plains/graduate-fellows-program)    
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AAAS/Science Program for Excellence in Science Award       
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2<sup>nd</sup> place, School of Natural Resources Elevator Speech Competition **$300**   
2015-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Resilience Alliance Young Scholar   
2015-18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Othmer Fellowship, University of Nebraska-Lincoln  **$24,000**     

## Outreach
####Blog Posts (links active) 
#####*for envirobites*    
- [Connecting to nature and understanding ecosystem services: the urban perspective](https://envirobites.org/2017/10/17/connecting-to-nature-and-understanding-ecosystem-services-the-urban-perspective/)    

#####*for the Resilience Alliance*  
- [Big data, big problems](http://resilience2017.org/blog/big-data-big-problems/)      
- [Panarchy in the Anthropocene](http://resilience2017.org/blog/panarchy-in-the-anthropocene/)      
- [Regime shifts, traps and how to deal with     them](http://resilience2017.org/blog/regime-shifts-traps-and-how-to-deal-with-them/)    
- [Connecting to nature and understanding ecosystem services: the urban perspective](http://resilience2017.org/blog/connecting-to-nature-and-understanding-ecosystem-services-the-urban-perspective/)    
- [Leadership resilience and your workplace](http://resilience2017.org/blog/leadership-resilience-and-your-workplace/)    

###Radio/podcasts
- [Interviewee, House Sparrow declines, Urban Wildlife Podcast](http://www.urbanwildlifecast.com/?p=139)  


## Relevant Skills 

**Quantitative ecological methods**     
&nbsp;&nbsp;&nbsp;&nbsp;-- Time series anlaysis      
&nbsp;&nbsp;&nbsp;&nbsp;-- Information theory   
&nbsp;&nbsp;&nbsp;&nbsp;-- Structural equation modeling    
&nbsp;&nbsp;&nbsp;&nbsp;-- Occupancy analyses    
&nbsp;&nbsp;&nbsp;&nbsp;-- Model based inference  
<!-- &nbsp;&nbsp;&nbsp;&nbsp;-- Utilizes both Bayesian and frequentist approaches   -->

**Statistical program proficiencies**  
&nbsp;&nbsp;&nbsp;&nbsp;-- Program R (advanced)  
&nbsp;&nbsp;&nbsp;&nbsp;-- SAS (novice)  
&nbsp;&nbsp;&nbsp;&nbsp;-- MatLab (novice)  

**Other**  
&nbsp;&nbsp;&nbsp;&nbsp;-- Local and remote research and writing collaborations     
&nbsp;&nbsp;&nbsp;&nbsp;-- Field and laboratory experimental design   
&nbsp;&nbsp;&nbsp;&nbsp;-- Data management

## Service
####*at the University of Nebraska-Lincoln*  
2018&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student representative, Natural Resources Diversity Initiative committee, School of Natural  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Resources, University of Nebraska-Lincoln  
2017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Key player in achieving institutional membership to the Association for Women in Science](http://news.unl.edu/newsrooms/today/article/university-is-institutional-partner-with-association-for-women-in-science/)
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student Representative, [Faculty Advisory Committee](http://snr.unl.edu/employeeinfo/people/committee/facultyadvisory.asp), School of Natural Resources   
2016-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student Representative, Digital Team, School of Natural Resources  
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Organizer, Association for Women in Science [Mentor Workshop](http://snr.unl.edu/registration/AWISMentor/MentorMenteeRegistrationAttendanceCap.aspx?utm_source=Google&utm_medium=email&utm_term=&utm_content=&utm_campaign=AWIS+Workshop)   
2016&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Seminar Coordinator](http://unlcms.unl.edu/snr/gsa/snr-gsa-seminar-coordinators), School of Natural Resources      
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founder & President, Natural Resources Diversity Initiative student group     
2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department Representative Representative, Graduate Student Association   
2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founder, Affiliate Chapter of the Association for Women in Science   

####*to the profession*    

2015-16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Student liaison, [Urban Ecosystem Ecology Section](http://www.esa.org/urbanecology/),  Ecological Society of America   

## Peer-reviews conducted
Ecological Modelling (2)
Wilson Journal of Ornithology (3)

<!-- ## Societal Memberships (since) -->
<!-- 2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Resilience Alliance    -->
<!-- 2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ecological Society of America    -->
<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Applied Ecology*, *Urban Ecosystem Ecology*, & *Student* sections   -->
<!-- 2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wilson Ornithological Society  -->
