---
author: Jessica L. Burnett, Ph.D.  
return-address: 
  - 300 E St. SW
  - Washington, D.C. 20017
address:
  - Technical and Professional Internships
  - Oak Ridge National Laboratory
  
# subject: Research Ecologist Position \{https://www.usajobs.gov/GetJob/ViewDetails/587668600}
opening: Dear Internship Committee, 
closing: Sincerely,
signature: Jessica L. Burnett, Ph.D. 

output: komaletter::komaletter
---

I am pleased to recommend Delaney Bellis for an ORNL TPI. During her internship at NASA Headquarters, where she produced a number of high-quality communications and outreach products, Delaney consistently demonstrated exceptional skills and qualities.

Delaney approaches every challenge with a positive attitude and a collaborative spirit, effectively navigating bureaucratic obstacles and contributing positively to team efforts. She has consistently shown an ability to adapt to time and bureaucratic challenges and pressures, and demonstrated an ability to do so in both a team and an independent environment.  

Her proactive approach to learning and willingness to seek out new information reflect her commitment to personal and professional growth. Delaney is clearly a highly creative person with a passion for effectively and *accurately* communicating science to a variety of audiences. For example, she joined an environment where she wasn't an expert in the topic at hand (remote sensing), but nevertheless she both worked to understand the content in an efficient manner, and work with her colleagues and superiors to ensure her products were scientifically accurate.

Delaney's strong work ethic and attention to detail ensure that she consistently delivers high-quality results, even when managing multiple tasks simultaneously. In just under a two months, Delaney delivered several high-quality and high-impact products. For example, she produced drafted and finalized a logo design over over a ~1 month period, all while soliciting and incorporating the opinions and criticism of several key stakeholders. Under similar circumstances, she also delivered both a newsletter template and quarterly product, which has since received the attention of several other NASA programs. 

In summary, Delaney Bellis is a capable and dedicated individual with the potential to excel in any endeavor she pursues. She will be sorely missed at NASA.