---
author: Jessica L. Burnett, Ph.D.  
return-address: 
  - 339 N Grant St
  - Denver, CO 80203
address:

  
# subject: Biologist \{https://www.usajobs.gov/GetJob/ViewDetails/592502500}
opening: Dr. Blomquist,
closing: Sincerely,
signature: Jessica L. Burnett, Ph.D.

output: komaletter::komaletter
---

I am excited to apply for the position of Biologist in the new Branch of SSA Science Support. I am currently a Research Ecologist (GS 12-2) and Mendenhall Postdoctoral Fellow in the Bioanalytics and Innovations Lab of the US Geological Survey's Core Science Systems [Science Analytics and Synthesis](https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis/about) group. 

I am a trained ecologist with a strong background in scientific data and information management, analysis of long-term monitoring data, software development, and avian ecology. My research largely operates at the intersection of ecological data and information synthesis, applied statistics, and digital scientific workflows. My work is largely motivated by two things. First, the perpetual disparity among the (actionable) science needs of natural resource practitioners and policy makers, and the budgetary resource availabity obtain actionable science. Second, ecological data is expensive, noisy, and often disparate. Leveraging **extant data, infomration, and knowledge** is vital to using informing natural resource decision processes whilst maintaining efficient use of taxpayer dollars under limited budgets. 

As a Mendenhall Postdoctoral Fellow in the US Geological Survey, I have worked closely with federal, state, and university researchers, decision makers, and natural resource managers to identify opportunities for improved **organizational and disciplinary knowledge management**. Knowledge management systems comprise the data, information, tools, workflows, and human resources used to create, share, and evolve understanding, or knowledge. My research in this area focuses on (i) scientific software development, (ii) creating, evaluating and communicating interactive tools (e.g., web applications, dynamic quantitative reports) for natural resource practitioners, and (iii) understanding and improving the role of ecological data for science producers and science users alike (using both quantitative and qualitative methods). Such systems for creating and transferring scientific understanding contributes to effective use of societal resources and improves the efficiency by which science is perpetuated.

My skills in scientific data management, statistical data analysis, ecoinformatics, and knowledge management will best contribute to the scientific and informational workflows informing BSSS science and acitivities. 
- ESIP lab project -- SWAP , better documenting report inputs such taht they are traceable, sustainably stored, and interoperable with other data and finormaiton sources
- Over the past year I have been 'mapping' the connectivity of FWS activities, data and organizations to understand how data and information flows in and outside the Service. This effort is ultimately to identify opportunities for facilitating efficient data and information flows within and among federal, state, and non-profit agencies in the U.S. The Figure below is not comprehensive, yet demonstrates both the connecitivities and complexities within the Service. C






to the design and implementation of how data, information, and knowledge is discovered, obtained, documented, tranferred, and communicated among the BSSS, BSSS stakeholders, and partnering agencies. 


 will use the best available science to inform monitoring program design and data analysis. My experience working closely with natural resource practitioners at many levels, including federal agency Deputy ADs, academic research scientists, international consortiums, and state agency biologists, has provided me with the skills and understanding required to identify the science needs of partners, and to provide timely, actionable science for decision makers and other stakeholders in your Region. Importantly, my research surrounding digital scientific workflows and communications will help improve the efficiency by which BLM and partner monitoring programs are conducted, documented, preserved, interpreted, and communicated.

Additional documents are enclosed in my USA Jobs applications. Please feel free to contact me if supplemental information or additional references are required. I look forward to your reply, and best of luck with your search. 
