---
author: Jessica L. Burnett, Ph.D.  
return-address: 
  - 339 N Grant Street
  - Denver, Colorado USA 80203
subject: Application for Advisory Committee, Planning for Open Grants
opening: To the Committee,
closing: Sincerely,
signature: Jessica L. Burnett, Ph.D.
output: komaletter::komaletter
---

As I have benefited from and contributed to Open Grants since learning of it a few years ago and I am excited to put my name forth as an applicant for this Planning phase of the project. I am currently a research ecologist and Mendenhall postdoctoral fellow at the U.S. Geological Survey. As a first generation college student I, perhaps unfortunately, have developed a deep understanding of how important awareness and access are to individual success (at least, in academics and STEM fields). Open Grants is one of the few tools that, from my perspective, can have an almost tangible impact on its users. Of course, I need not explain the current and potential value of Open Grants and similar efforts to this readership. 

I am applying to join this Planning Committee for three reasons to ensure that the committee has at least one person who is keen to bring one or more of the following important perspectives to the discussions: first gen, individuals with disabilities in STEM, and postdoctoral scholars/recent grads. However, I should note that of the three areas identified in the call for applications, I could likely only contribute to one (STEM fellowships). 

In the likely event I am not invited to join this team, I wish to use the remainder of this letter to suggest some potential points of discussion (though I hope there will be a public commenting period/invited feedback on your funding proposals in the future!):
1. Awareness campaigns to historically under-represented groups and groups that might benefit most from access to Open Grants materials should be prioritized in funding requests for outreach/advertising. Notably, an often-overlooked group who may disproportionately benefit from awareness of and access to Open Grants submissions is individuals with disabilities (e.g., see [Disabled in STEM](https://disabledinstem.wordpress.com/)). 
1. Open Grants teams should identify community liaisons who can effectively spread awareness and generate the openness/transparency culture (which I assume is an aim) to their professional networks. One such model for paid liaisons can be seen in the [ESIP Community Fellows](https://www.esipfed.org/collaboration-updates/welcome-2021-community-fellows) program. (I would be remiss if I did not suggest also targeting liaisons for U.S. federal agencies)

Finally, I wish to note here that, as a current U.S. federal employee I cannot accept any honorarium beyond direct reimbursement to the U.S. Geological Survey. I highlight this not because I aim to provide incentive to choose me as a contributor but rather for the opposite reason––if there are individuals who can provide similar perspectives as I have mentioned here, I do hope they are given preference over myself. I am very excited to see Open Grants is poised for such growth. I look forward to what’s in store for this community, and will continue on as a contributor, user, and advocate. 

<!-- https://www.ogrants.org/call-for-participation.html -->
