---
author: Jessica L. Burnett, Ph.D.  
return-address: 
  - 300 E St SW MS 3Z45
  - Washington, D.C. 20546
address:
  - Dr. Jessica Burnett
  - AAAS Science & Technology Policy Fellow
  - NASA Earth Science Division
  
opening: To the review board,
closing: Sincerely,
signature: Jessica L. Burnett, Ph.D.

output: komaletter::komaletter
---

As the sole AAAS Science and Technology Policy Fellow at NASA, privileged to collaborate closely with Dr. Jessica Welch for the past 6 months, I wholeheartedly endorse her proposed promotion from TP02 to TP03. Despite our relatively short timeframe working together, Dr. Welch has left a positive mark on both myself and my colleagues at NASA Headquarters. In this period, I've had the opportunity to witness remarkable professional and character qualities in her that align seamlessly with the promotion criteria of "Knowledge," "Scope," and "Liaison."

Dr. Welch possesses a wealth of subject matter expertise in Earth observations data, tools, and digital resources, particularly within NASA. Her contributions have significantly benefited stakeholders of the NASA Earth Science Division Ecological Conservation Applications Area. Whenever confronted with inquiries from the ecological conservation community, Dr. Welch stands out as a trusted and reliable subject matter expert. In the one-on-one interactions I've observed, end users consistently walk away with far deeper knowledge and capacity beyond their initial expectations. Her ability to engage effectively with stakeholders not only showcases her technical and subject matter expertise but also highlights her exceptional interpersonal skills.

Notably, Dr. Welch's distinction as the sole NASA representative nominated for the position of Federal Coordinating Lead Author (FCLA) for the Nation's inaugural National Nature Assessment (NNA1) underscores her exceptional qualifications. In addition to disciplinary and technical subject matter expertise, this prestigious role demands robust interpersonal skills, tact, passion, energy, and the ability to communicate effectively with scientists and decision-makers alike. The careful consideration inherent in nominations for such a pivotal role reflects the enduring and positive impression Dr. Welch has left on myself and colleagues at NASA Headquarters.

Dr. Welch's passion for biodiversity science and her adept communication skills position her as an exceptional ambassador for NASA Earth observations and the broader scientific community. Combined with her recent successful nomination for the NNA FCLA position, Dr. Jessica Welch proves a valuable and important member of the NASA team.
