---
author: Jessica L. Burnett, Ph.D.  
return-address: 
  - 85 S. Union Blvd \#563
  - Lakewood, CO 80228
address:
  - Dr. Michael Schwartz
  - Rocky Mountain Research Station
  - US Forest Service
  
# subject: Research Ecologist Position \{https://www.usajobs.gov/GetJob/ViewDetails/587668600}
opening: Dr. Schwartz and Rocky Mountain Research Station Colleagues,
closing: Sincerely,
signature: Jessica L. Burnett, Ph.D.

output: komaletter::komaletter
---

I am pleased to apply for the Research Ecologist Position serving the US Forest Service Rocky Mountain Region in the Rocky Mountain Research Station. I am currently a Research Ecologist and Mendenhall Postdoctoral Fellow in the Bioanalytics and Innovations Lab of the US Geological Survey's Core Science Systems Science Analytics and Synthesis group. I am excited at the opportunity to develop a research program that can simultaneously contribute to ecological understanding and contribute to more efficient and effective public lands management.      

I am a trained ecologist with a strong background in quantitative ecology, data science, software development, and avian and invasion ecology. My research largely operates at the intersection of data and information synthesis, applied statistics, and digital scientific workflows. My work is largely motivated by two things. First, the perpetual disparity among the (actionable) science needs of natural resource practitioners and the informational and budgetary resource availabity to those same practitioners. Second, ecological data is expensive, noisy, and often disparate--the ability to re-use existing data and design future monitoring efforts that are broadly applicable is program for gaining actionable insights under shrinking budgets. 

Abrupt and unexpected changes in ecological systems (also referred to as regime shifts) can lead to undesirable changes, and regime shifts are apparently being exacerbated by impacts of the anthropocene. In the research community, there is an ongoing thrust to apply statistical methods to observational data to both identify and forecast these changes. However, the relevance of such quantitative methods for forecasting such changes are not tested nor are applied to real-world systems. As a doctoral student, I conducted research that evaluated the efficacy of statistical and mathematical methods for identifying regime shifts in ecological communities. I co-lead an international and funded working group that continues to develop and evaluate *feasible*, applied statistical methods for identifying abrupt changes in observational data for terrestrial and aquatic systems. 

As a Mendenhall Postdoctoral Fellow in the US Geological Survey, I have worked closely with federal, state, and university researchers, decision makers, and natural resource managers to develop knowledge management systems for avian ecology and conservation in North Amerca. Knowledge management systems comprise the data, information, tools, workflows, and human resources used to create, share, and evolve understanding, or knowledge. My research in this area focuses on (i) scientific software development, (ii) creating, evaluating and communicating digital interactive tools (e.g., web applications, dynamic reports, scientific software) for natural resource science and management, and (iii) identifying and improving data and information flows and synthesis. Such systems for creating and transferring scientific knowledge contributes to effecetive use of government resources and improves the efficiency by which science is conducted.

As a Research Ecologist within the Rocky Mountain, I will continue to conduct research and science support at the nexus of applied ecological statistics, environmental data science and synthesis, and digital scientific workflows. My experience working closely with natural resource practitioners at many levels, including federal agency Deputy ADs, academic research scientists, international consortiums for ecological data collection, and state agency biologists have provided me with the skills and understanding required to simultaneously develop a relevant and impactful research program and create timely, actionable science for Forest Service decision makers and other stakeholders in the Region. Importantly, my research surrounding digital scientific workflows and communications aim to impact individual research and programs within and beyond the agency.     

Additional documents are enclosed in my USA Jobs applications. Please feel free to contact me if supplemental information or additional references are required. I look forward to your reply, and best of luck with your search. 
