---
output: 
  pdf_document:
      latex_engine: pdflatex
      template: cv-latex.tex
  md_document:
    variant: gfm
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding,
         output_format = "all") })
geometry: margin=.7in
title: "Extended CV"
author: JESSICA L. BURNETT
orcid:  0000-0002-0896-5099
fontawesome: yes
email: jburnett@usgs.gov
# github: trashbirdecology
phone: "+1 720-730-0974"
# updated: no
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue(munsell)
linkcolor: maroon
linkedin: burnettjl
jobtitle: Research Ecologist & Mendenhall Postdoctoral Fellow
---
# Education
**Ph.D.** Natural Resource Sciences (Applied Ecology), University of Nebraska-Lincoln \hfill 2019  
**M.Sc.** Wildlife Ecology & Conservation, University of Florida \hfill 2015  
**B.Sc.** Wildlife Ecology & Conservation University of Florida \hfill 2013  
**A.A.** General studies Valencia Community College \hfill 2010

# Research Experience
**Research Ecologist** (GS-12), U.S. Geological Survey, Lakewood, Colorado, USA   
September 2019 - present   

- Developed integrated Bayesian modeling framework and workflow for estimating abundance and trends of birds in North America. 
- Evaluated the users and uses of a USGS data program using informatics and social science methods. Made recommendations to program administrations for improving value of agency's data assets to stakeholders.
- Co-led grant application (funded) to Canadian Institute for Ecology and Evolution to fund a year-long working group. Developed software and database for analyzing environmental data for abrupt change and regime shifts.
- Co-led grant application (funded) for Earth Science Information Partnership working group. Developed knowledge graph for assisting with the documentation and development of U.S. State Wildlife Action Plans.
- Authored and co-authored 3 peer-reviewed research articles, 1 federal agency report, and multiple R packages. 

**Graduate Research Assistant**, Nebraska Cooperative Fish & Wildlife Research Unit, University of Nebraska-Lincoln (UNL), Nebraska  
August 2015 - August 2019  

- Developed and evaluated statistical methods for detecting abrupt change in ecological and paleoecological communities.
- Worked closely with U.S. military base land managers to meet research needs and communicate results. 
- Published 7 peer-reviewed articles, 1 book chapter, 3 reports, and 5 software packages.
- Co-developed and taught week-long scientific programming workshop to state wildlife agency practitioners and university students.
- Co-founder of the university's Chapter of the Association for Women in Science (AWIS). Worked closely with university administration to initiate institutional membership in AWIS. Organized mentoring workshop. 

**Young Scholar**, Applied Systems Analysis Research Group, International Institute for Applied Systems Analysis (IIASA), Austria  
May 2018 - September 2018  

- Developed novel method for detecting regime shifts in paleoecological data (system velocity). 
- Conducted research with an international team of applied mathematicians and systems scientists. Presented research in an international forum.
- Organized seminar on Network Analysis in Ecology. 
- 1 of 51 scholars from 27 countries of ~400 applicants.


**Graduate Teaching Assistant**, Department of Wildlife Ecology & Conservation, University of Florida, Florida, USA  
August 2013 - August 2015   

- Taught population ecology, invasion ecology, and scientific programming to university students. 
- Published 2 peer-reviewed scientific articles. 
- Led grant application to develop nature trail and receive nature-based educational materials for a local, non-profit organized aimed to reduce recidivism among community youth. Organized after school activities of hands-on wildlife interactions with youth. 


**Geospatial Analyst Intern**, Florida Fish and Wildlife Research Institute, Gainesville, FL  
April 2012 -  August 2012  

- Designed and completed geospatial analysis of raptor and owl nest locations and nesting success. 
- Performed ground-truthing of habitat data. 


**Undergraduate Research Assistant**, Avian Ecology and Conservation Lab, University of Florida  
January 2011 - April 2012    

- Developed and published field method for improved detection of Red-shouldered Hawk (*Buteo lineatus*). 
- Managed laboratory's bird banding database. 
- After school tutor for low-income middle school students at local library. 

**Crew Leader and Smithsonian Fellow**, Neighborhood Nestwatch Program, Gainesville, Florida   
May - July 2012 & April - August 2013   

- Trained and led team of 3 bird banding technicians. 
- Led community outreach programs for youth in state-sponsored after school and summer programs. 
- Recruited and trained participatory scientists. 
- Created and distributed outreach materials for program participants. 


# Publications 

1. **Burnett, J.L.**, R. Dale, C.Y. Hou, G. Palomo-Muñoz, K.S. Whitney, S. Aulenbach, R.S. Bristol, D. Valle, and T. Wellman (2021). Ten Simple Rules for Creating a Scientific Web Application.  _PLoS Computational Biology_

1. Erickson, R.A., **Burnett, J.L.**, M.T. Wiltermuth, E.A. Bulliner, and L. Hsu (2021). Paths to computational fluency for natural resource educators, researchers, and managers. _Natural Resource Modeling_ [DOI: 10.1111/nrm.12318](https://onlinelibrary.wiley.com/doi/10.1111/nrm.12318?af=R)

1. **Burnett, J.L.** and C.R. Allen. 2020. Continental analysis of invasive Birds:  North America *in* Downs, C.T. and Hart, L.A. (eds) Invasive Birds: Global Trends and Impacts. CABI International, Wallingford, UK, pp. 278-294. 

1. **Burnett, J.L.**, L.S. Wszola, and G. Palomo-Muñoz. 2019. bbsAssistant: An R package for downloading and handling data and information from the North American Breeding Bird Survey. Journal of Open Source Software, 4(44), 1768, DOI: [10.21105/joss.01768](https://doi.org/10.21105/joss.01768)

1. Donovan, V.M., **Burnett, J.L.**, C.H. Bielski, H.E. Birge, R. Bevans, D. Twidwell, and C.R. Allen. 2018. Social-ecological landscape patterns predict woody encroachment from native tree plantings in a temperate grassland *Ecology and Evolution* 8(19): 9624-9632 DOI:10.1002/ece3.4340

1.  **Burnett, J.L.**, K.L. Pope, A. Wong, C.R. Allen, D.M. Haak, B.J. Stephen, and D.R. Uden. 2018. Thermal tolerance limits of the invasive Chinese mysterysnail *Bellamya chinensis* and implications for management. *American Malacological Bulletin* 36(1): 140-144 DOI:10.4003/006.036.0106   

1. Roberts, C.P., D. Twidwell, **Burnett, J.L.**, V.M. Donovan, C. Wonkka, C.H. Bielski, A.S. Garmestani, D.G. Angeler, T. Eason, B.W. Allred, M.O. Jones, D.E. Naugle, S. Sundstrom, C.R. Allen . 2018. Early warnings for state transitions. *Rangeland Ecology and Management* DOI:10.1016/j.rama.2018.04.012     

1. La Sorte, F.A., C.A. Lepczyk, **Burnett, J.L.**, A. Hurlbert, M. Tingley, and B. Zuckerberg. 2018. Opportunities and challenges for big data ornithology. *The Condor* 120(2): 414-426 DOI:0.1650/CONDOR-17-206.1

1. Chuang, W.C., A.S. Garmestani, T. Eason, T.L. Spanbauer, H.B. Fried-Peterson, C. Roberts, S. Sundstrom, **Burnett, J.L.**, D. G. Angeler, B. Chaffin, L. Gunderson, D. Twidwell, C.R. Allen. 2018. Enhancing quantitative approaches for assessing ecological and community resilience. *Journal of Environmental Management* 213: 353-362 DOI:10.1016/j.jenvman.2018.01.083    

1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D. 2017. White Paper: Regime Shift Detection Using Fisher Information. Strategic Environmental Research and Development Program (SERDP RC 25-10), Department of Defense.  

1. Allen, C.R., Angeler, D.G., Twidwell, D., **Burnett, J.L.**, Roberts, C.P. 2017. Interim Report (RC 25-10): Global Change, Vulnerability, and Resilience: Management Options for an Uncertain Future. Strategic Environmental Research and Development Program (SERDP), Department of Defense.

1. Twidwell D., Bielski, C.H., **Burnett, J.L.**, Donovan, V.M., Wonkka, C.L. 2017. Review of LANDFIRE Biophysical Settings Models (BpS) in the Great Plains. LANDFIRE Project.   


1.  **Burnett, J.L.**, C.R. Allen, C.P. Roberts, M.Bomberger Brown, and M.P. Moulton. 2017. Eurasian Tree Sparrow (*Passer montanus*) range expansion in North America. *Biological Invasions* 19(1): 5-9 DOI:10.1007/s10530-016-1273-4  

1.  **Burnett, J.L.** and K.E. Sieving. 2016. Songbird distress call as a detection enhancement method and application to Red-shouldered Hawks (*Buteo lineatus*). *Florida Field Naturalist* 44(4):157-168      

1. C.R. Allen, H.E. Birge, S.L. Bartlet-Hunt, R.A. Bevans, **Burnett, J.L.**, B.A. Cosens, X. Cai, A.S. Garmestani, I. Linkov, E.A. Scott, M.D. Solomon, and D.R. Uden. 2016. Avoiding decline: Fostering resilience and sustainability in midsize cities. *Sustainability* 8(9):844-868 DOI:10.3390/su8090844   

1. **Burnett, J.L.** and M.P. Moulton. 2015. Recent trends in House Sparrow (*Passer domesticus*) distribution and abundance in Gainesville, Alachua County, Florida. *Florida Field Naturalist* 43(4):167-172   


<!-- ## Lead authored, in review -->

<!-- 1. **Burnett, J.L.**, R. Wilcox, B. Stephen, D. Haak, D. Uden, C.R. Allen, and K. Pope. Shell strength does not limit predation of an invasive snail species (Bellamya chinensis) by native fish. *In review at Malacological Bulletin* -->


# Research Grants
## Funded 
1. Wee, B., **Burnett, J.L.**, S. Aulenbach, W. Teng, R.A. Modeling data and information needs for avian conservation using Neo4j. Earth Science Information Partners Lab  (__$3,388__)
1. Pedersen, E., **Burnett, J.L.**, G. Simpson, C. Bahlai. __2020__. Creating a unified approach to evaluate regime shift detection methods. Canadian Institution for Ecology and Evolution (CIEE)  (__$10,000__)
1. **Burnett, J.L.**. __2019-21__. Mendenhall Postdoctoral Research, Core Science Systems Science Analytics and Synthesis, U.S. Geological Survey. (__$222,000__)
1.  **Burnett, J.L.**. __2018__ International Institute for Applied Systems Analysis (IIASA) [Young Scholar Summer Program](https://iiasa.ac.at/web/home/education/yssp/Young_Scientists_Summer_Program.html). Funding sources: National Academy of Sciences and University of Nebraska-Lincoln. (__$12,500__)
1. **Burnett, J.L.** __2013__. IFAS Extension Internship for Undergraduate Research, University of Florida. (__$2,200__)
1. **Burnett, J.L.** __2013__. Ordway-Swisher Biological Station Undergraduate Research Grant, University of Florida. (__$550__)


<!-- ## Not Funded   -->
<!-- 1. Pedersen, E., **Burnett, J.L.**, G. Simpson, C. Bahlai. Creating a unified approach to evaluate regime shift detection methods. Powell Center Synthesis Working Group, U.S. Geological Survey \hfill 2020  <!--__$166,642__  -->  
<!-- 1. Informing the design and deployment of a conservation tool, USAvian: learning through co-production, synthesizing lessons learned. Community for Data Integration, U.S. Geological Survey \hfill 2020 <!--  __$70,539__  --> 
<!-- 1. Benito, X., C. Bahlai, **J.L., Burnett**, E. Pedersen, and G. Simpson. SESYNC working group proposal.  \hfill  2019   -->
<!-- 1. **Burnett, J.L.**. Population Biology Program of Excellence (PoE) Postdoctoral Fellowship, University of Nebraska-Lincoln \hfill 2018   -->
<!-- 1. **Burnett, J.L.**, C.R. Allen, G. Sugihara, and H. Ye. Scale mismatches in ecological research and management: consequences and solutions through data management. Powell Center Synthesis Working Group, U.S. Geological Survey   \hfill 2018   -->
<!-- 1. **Burnett, J.L.** Mozilla Fellowship for Science \hfill 2016   -->
<!-- 1. **Burnett, J.L.** NSF Graduate Research Fellowship   \hfill 2012, 2013   -->

# Scientific Software and Source Code 
### Lifecycle: maturing, stable
1. **Burnett, J.L.**, L.S. Wszola, and G. Palomo-Munoz. 2019. [`bbsAssistant`](https://github.com/TrashBirdEcology/bbsAssistant): An R package for downloading and handling data and information from the North American Breeding Bird Survey: U.S. Geological Survey software release. DOI: [10.5066/P93W0EAW](https://doi.org/10.5066/P93W0EAW).
1. Price, N.B., C. Chizinski, and **Burnett, J.L.**. `radsets`. An R package for interactive, network-based visualizations of overlapping sets.  [Github:natbprice/radsets](https://natbprice.github.io/radsets/)
1. **Burnett, J.L.**, N.B. Price, and A.J. Tyre. [`distanceTravelled`](https://github.com/TrashBirdEcology/distancetravelled). An R package for calculating the distance traveled by a multispecies community along a time series. 
1. Price, N.B. and **Burnett, J.L.**. `tvdiff`.  An R package for numerical differentiation of noisy, non-smooth data. [Github:natbprice/tvdiff](https://github.com/natbprice/tvdiff) 

### Lifecycle: experimental
1. **Burnett, J.L.**, J.A. Royle, P. Howell [`bbsebird`](https://github.com/TrashBirdEcology/USAvian/): data integrated and Bayesian modeling of North American BBS and eBird data.

1. **Burnett, J.L.**, K.R. Burgio, A. Fournier [`USAvian`](https://github.com/TrashBirdEcology/USAvian/): An interactive map for connecting and visualizing the bird conservation and management networks in the U.S. 

1. **Burnett, J.L.**, X. Benito, and K. Braziunas. [`abruptdata`](http://github.com/regime-shifts/abruptdata). An R package and information repository for ecological datasets exhibiting abrupt change.

### Lifecycle: dormant
1. **Burnett, J.L.**, N.B. Price. [`regimeDetectionMeasures`](https://github.com/TrashBirdEcology/regimedetectionmeasures). An R package for calculating univariate and multivariate regime detection methods using community time series.  

# Select Honors & Awards
- USGS FY2021 Performance Award (2021)
- Invited focus group participant, NSF Missing Millions (2021)
- USGS FY2020 Performance Award (2020)
- Invited workshop participant, Future of Synthesis in Ecology, NCEAS (2020)
<!-- - School of Natural Resources, UNL (2019) \hfill __$750__ -->
<!-- - University of Nebraska Graduate Travel Fund (2019)                \hfill __$750__ -->
<!-- - Association for Women in Mathematical Biology (2019)               \hfill __$650__ -->
<!-- - School of Natural Resources travel award, UNL (2019) \hfill __$1050__ -->
- [Meritorious Graduate Student](http://snr.unl.edu/aboutus/what/awardscomplete.asp) award, School of Natural Resources, UNL (2018) \hfill __$500__
- National Academy of Sciences research award  (2018) \hfill __$5,500__
- Invited Participant, [Workshop for Women in Mathematical Biology, NIMBIOS](http://www.nimbios.org/education/WS_wwmb) (2018) \hfill __$900__
<!-- - National Science Foundation & NimBios (2018) \hfill __$550__ -->
<!-- - Center for Great Plains Studies, UNL *(3x recipient)* (2017-18) \hfill __totaling $3,000__  -->
<!-- - Kellogg Biological Station, Michigan State University (2017) \hfill __$500__ -->
- Big Ten Academic Alliance Traveling Scholar (2017)
<!-- - Nelson Memorial Fellowship, UNL *(3x recipient)* (2016-18) \hfill  __totaling $3,217__  -->
<!-- - 2<sup>nd</sup> place, School of Natural Resources Elevator Speech Competition (2016) \hfill __$300__  -->
<!-- - American Ornithologists' Union travel award (2016)  \hfill __$250__  -->
- Fling Fellow, UNL (2016)  \hfill __$20,000__ 
- Othmer Fellow (1 university-wide recipient annually), UNL (2016) \hfill __$24,000__ 
<!-- - AAAS/Science Program for Excellence in Science Award (2016) -->
- Graduate Fellow, Center for Great Plains Studies,UNL (2016)
- Resilience Alliance Young Scholar, The Resilience Alliance (2015-2017) \hfill
<!-- - NSF Diversity Travel Award, Southeastern Ecology and Evolution Conference (2015) \hfill __$650__ -->
<!-- - Graduate Student Council travel award, University of Florida (2015) \hfill __$350__ -->
<!-- - Office of Research, University of Florida (2015)  \hfill __$350__ -->
<!-- - Department of Wildlife Ecology & Conservation travel award, University of Florida *(2x recipient)* (2014)   \hfill __$500__ -->
<!-- - Office of the Dean, Institute of Food and Agricultural Sciences, University of Florida (2013) \hfill __$750__ -->
<!-- - American Ornithologists' Union Undergraduate Student Membership Award (2013) \hfill  -->

<!-- # Teaching   -->
<!-- ## Course Development -->
<!-- **Reproducible Research and Collaboration in Ecology**. Course materials can be found on [GitHub](https://github.com/TrashBirdEcology/courses/tree/master/rr_course). -->

<!-- ## Instruction -->
<!-- **Co-instructor** Introduction to Applied Ecological Statistics, Kearney, NE \hfill 2017   -->
<!-- - Week-long workshop for employees of the Nebraska Game and Parks Commission employees -->

<!-- **Instructor** Introduction to Prorgam R \hfill 2017   -->
<!-- - Designed and taught a series of half-day workshops for graduate students -->
<!-- - Basics of data management and analysis using Program R -->

<!-- **Guest Lecturer** Module: using citizen science data to understand ecological invasions; Course: Avian Invasions  \hfill 2016   -->
<!-- - Designed and taught series of lectures on citizen science data use and applications -->

<!-- **Teaching Assistant** Wildlife Population Ecology, Department of Wildlife Ecology & Conservation, University of Florida \hfill 2015   -->
<!-- - Led quantitative laboratory sessions -->

<!-- **Teaching Assistant** Ecological Statistics, Department of Wildlife Ecology & Conservation, University of Florida \hfill 2015     -->
<!-- - Led and moderate discussions -->
<!-- - Provided statistical support   -->

<!-- **Guest Lecturer** Wetland birds module, Florida Master Naturalist \hfill 2013   -->
<!-- - Designed and taught module on wetland bird identification and ecology -->

# Conference Symposia and Special Session Organizer  
1. Using the integrated modelling framework to bridge science and decision making: advances, applications, and opportunities. Co-organizer with J.A. Royle. Ecological Society of America conference (2020)
1. Bridging the gap between science and decision-making through the rapid prototyping of decision support tools. Co-organizer with D. Valle and L.S. Wszola. Ecological Society of America conference (2020)
1. Opportunities and Challenges in Big Data Ornithology. Co-organizer with F.A. LaSorte and C.A. Lepczyk. North American Ornithological Conference V, Washington, D.C. (2016)

# Select Presentations (last 5 years)
## Invited 
1. Integrating data and information to enhance the digital efficiency of wildlife conservation and management. North American Ornithological Conference  (2020)

1. Invited Seminar Speaker, Regime Detection Measures for the Practical Ecologist, Department of Wildlife Ecology & Conservation, University of Florida (2019)

1. Detecting abrupt change in bird community time series using distance traveled. *Association for Women in Math Biology Symposium*, Special session "Current Challenges in Mathematical Biology ", Houston, TX  (2019)

<!-- 1. Decline of the Once-Ubiquitous House Sparrow in North America. *Nebraska Invasive Species Council*, Lincoln, NE  (2015)      -->

## Contributed
1. **Burnett, J.L.**, N.B. Price, and A.J. Tyre. A novel method for tracking ecosystem trajectory and abrupt change in space-time: distance traveled. *International Association for Landscape Ecology*, Oral presentation. Fort Collins, CO (2019)

1. **Burnett, J.L.**, R. Crystal-Ornelas, D. Fogarty, K. Hogan, C.R. Allen, M. Bomberger Brown, D. Twidwell, and C.A. Lepczyk. Impacts of non-native birds on native wildlife in urban ecosystems: where is the evidence?  *Natural Areas Conference*, Oral presentation. Indiana (2018)

1. **Burnett, J.L.**. Advances in ecological regime shift detection, *International Institute for Applied Systems Analysis*, Oral presentation. Laxenburg, Austria  (2018)

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. Community velocity as a regime shift detection method. *Great Plains Grassland Summit*, Poster presentation. Denver, Colorado (2018)

1. **Burnett, J.L.**, L. Wszola, N. Mirochnitchenko, E. Stuber, M. Bomberger Brown, C.R. Allen, D. Twidwell, and J.P. Carroll (presenter).  Gray partridge distribution in North America: Changing landscapes and environment for an introduced species. Perdix XIV and IUGB, Oral presentation by JPC, Montpellier, France (2017)

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. System trajectory and Fisher information as early-warning indicators of ecological regime shifts. *Resilience 2017: Resilience Frontiers for Global Sustainability*, Poster presentation. Stockholm, Sweden (2017)

<!-- 1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. System trajectory and Fisher information as early-warning indicators of ecological regime shifts. *Ecological Society of America*, Poster presentation. Portland, OR (2017) -->

<!-- 1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Ecological Regime Shifts in the Central Great Plains. *Great Plains Symposium*, Oral presentation. Nebraska Innovation Campus, Lincoln, NE (2017) -->

<!-- 1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Using Big Data to Detect Regime Shifts in Space and Time. *North American Ornithological Conference VI*, Poster presentation. Smithsonian Migratory Bird Institute, Washington, D.C. (2016) -->

<!-- 1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? Southeastern Ecology and Evolution Conference, Oral presentation. University of Georgia, Athens, GA (2015)   -->

<!-- 1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M.L., and Robinson, S.K. Are House Sparrow declines a byproduct of urban greening? *American Ornithologists' Union and Cooper Ornithological Society Annual Meeting*, Poster presentation. Norman, OK (2015)   -->

<!-- 1. **Burnett, J.L.**, Moulton, M.P., and Sieving, K.E. House sparrow: the decline of a once ubiquitous, invasive species. *Florida Chapter of The Wildlife Society Annual Conference*, Poster presentation. Safety Harbor, FL (2014) -->

<!-- 1. **Burnett, J.L.**, Moulton, M. P., Sieving, K.E., Avery, M.L., and Robinson, S.K. House Sparrow decline and distribution in North Central Florida. *Florida Cooperative Fish and Wildlife Research Unit annual cooperators meeting*, Poster presentation. Gainesville, FL (2014)   -->

<!-- 1. **Burnett, J.L.** and Sieving, K.E. Detecting birds of prey using tufted titmouse distress calls. *USGS Florida Cooperative Fish and Wildlife Research Unit Committee Meeting*, Poster presentation. Gainesville, FL, (2013) -->

<!-- 1. **Burnett, J.L.** and Sieving, K.E. Do actual and perceived risks of small forest birds align? *Florida Ornithological Society Conference, Oral presentation*, St. Petersburg, FL (2013) -->

<!-- 1. **Burnett, J.L.** and Sieving, K.E. Perceived predation risks of small forest birds. *Association of Field Ornithologists Annual Conference*, Poster presentation. Venus, FL (2013) -->


# Select Certifications, Workshops, and Professional Development Training
- Leadership and Management Skills for Non-managers, Management Concepts \hfill 2021 
- USGS 12-month Mentoring Program (mentee) \hfill 2020-21 
- USGS Principled Centered Leadership (USGS-PCL) \hfill   2020
- Gauging Your Leadership Performance \hfill 2020
- Defining Alternative Solutions to a Problem \hfill   2020
- Aligning Goals and Priorities to Manage Time \hfill   2020
- Structured Decision Making Workshop (observer) \hfill 2020
- High Performance Computing in R and Python \hfill 2020
- Software Carpentries \hfill 2015
- Basic Wildland Firefighting (SF-1390, SF-190) \hfill 2013
