---
output: 
  pdf_document:
      latex_engine: pdflatex
      template: cv-latex.tex
  # md_document:
  #   variant: markdown_github
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding,
         output_format = "all") })
geometry: margin=.7in
title: "CV"
author: JESSICA L. BURNETT
orcid:  0000-0002-0896-5099
fontawesome: yes
email: jburnett@usgs.gov
github: trashbirdecology
twitter: trashbirdecol
phone: "+1 352 792 5425"
updated: yes
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---
# (a) Professional Preparation
**Ph.D., Natural Resource Sciences, Specialization Applied Ecology** \hfill 2015 - 19  
School of Natural Resources, University of Nebraska-Lincoln, Nebrasaka USA

**M.Sc., Wildlife Ecology & Conservation** \hfill 2013 - 15  
Department of Wildlife Ecology & Conservation, University of Florida, Florida USA

**B.Sc. Wildlife Ecology & Conservation** \hfill 2010 - 13  
Department of Wildlife Ecology & Conservation, University of Florida, Florida USA

# (b) Positions Held
**Research Ecologist & Mendenhall Postdoctoral Fellow**  \hfill September 2019 - present  
Science Analytics and Synthesis, Core Science Systems  
U.S. Geological Survey, Lakewood, Colorado, USA

**Graduate Research Assistant**   \hfill August 2015 - August 2019  
Nebraska Cooperative Fish & Wildlife Research Unit   
School of Natural Resources
University of Nebraska-Lincoln, Nebraska, USA

**Young Scholar**    \hfill May 2018 - September 2018  
Applied Systems Analysis Research Group  
International Institute for Applied Systems Analysis 
Laxenburg, Austria

**Graduate Teaching Assistant**   \hfill August 2013 - August 2015   
Department of Wildlife Ecology & Conservation  
University of Florida, Florida, USA

# (c) Select Publications (10 published, 3 in review, 1 published book chapter)

## (i) Publications relating to proposed research _

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre,  D.G. Angeler, T. Eason, D. Twidwell., and C.R. Allen. Deconstructing the steps for calculating Fisher Information as a measure of abrupt change in ecological systems. *under review at Ecological Modelling*

1. **Burnett, J.L.**. 2019. Regime Detection Measures for the Practical Ecologist. 

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre,  D.G. Angeler, T. Eason, D. Twidwell., and C.R. Allen. Deconstructing the steps for calculating Fisher Information as a measure of abrupt change in ecological systems. *in review at Ecological Modelling*

1. **Burnett, J.L.**, G. Munoz-Palomo, and L. Wszola.*under review at Journal of Open Source Software* `bbsAssistant`. 2019. An R package for downloading and manipulating the North American Breeding Bird Survey data. https://github.com/TrashBirdEcology/bbsAssistant/blob/master/man/bbsAssistant_0.0.1.pdf [Github:trashbirdecology/bbsAssistant](https://github.com/TrashBirdEcology/bbsAssistant)

1. Price, N.B. and **J.L. Burnett**. `tvdiff`. 2019.  An R package for numerical differentiation of noisy, non-smooth data. [Github:natbprice/tvdiff](https://github.com/natbprice/tvdiff) 

1. **Burnett, J.L.**, N.B. Price. 2019. `regimeDetectionMeasures`. An R package for calculating univariate and multivariate regime detection methods using community time series.  [Github:trashbirdecology/regimedetectionmeasures](https://github.com/TrashBirdEcology/regimedetectionmeasures)

1. Roberts, C.P., D. Twidwell, **J.L. Burnett**, V.M. Donovan, C. Wonkka, C.H. Bielski, A.S. Garmestani, D.G. Angeler, T. Eason, B.W. Allred, M.O. Jones, D.E. Naugle, S. Sundstrom, C.R. Allen,  (2018) Early warnings for state transitions. *Rangeland Ecology and Management* DOI:10.1016/j.rama.2018.04.012

1. **Burnett, J.L.**, N.B. Price, and A.J. Tyre. 2018. `distanceTravelled`. An R package for calculating the distance traveled by a multispecies community along a time series. [Github:trashbirdecology/distancetravelled](https://github.com/TrashBirdEcology/distancetravelled)

1. Chuang, W.C., A.S. Garmestani, T. Eason, T.L. Spanbauer, H.B. Fried-Peterson, C. Roberts, S. Sundstrom, **J.L. Burnett**, D. G. Angeler, B. Chaffin, L. Gunderson, D. Twidwell, C.R. Allen. 2018. Enhancing quantitative approaches for assessing ecological and community resilience. *Journal of Environmental Management* 213: 353-362 DOI:10.1016/j.jenvman.2018.01.083    

## (ii) Additional significant products
1. La Sorte, F.A., C.A. Lepczyk, **J.L. Burnett**, A. Hurlbert, M. Tingley, and B. Zuckerberg. 2018. Opportunities and challenges for big data ornithology. *The Condor* 120(2): 414-426 DOI:0.1650/CONDOR-17-206.1
1.  **Burnett, J.L.**, C.R. Allen, C.P. Roberts, M.Bomberger Brown, and M.P. Moulton. 2017. Eurasian Tree Sparrow (*Passer montanus*) range expansion in North America. *Biological Invasions* 19(1): 5-9 DOI:10.1007/s10530-016-1273-4  
1. **Burnett, J.L.**, G. Munoz-Palomo, and L. Wszola.*under review at Journal of Open Source Software* `bbsAssistant`. 2019. An R package for downloading and manipulating the North American Breeding Bird Survey data. https://github.com/TrashBirdEcology/bbsAssistant/blob/master/man/bbsAssistant_0.0.1.pdf [Github:trashbirdecology/bbsAssistant](https://github.com/TrashBirdEcology/bbsAssistant)

# (c) Synergistic activities
1. **Instructor** Introduction to Applied Ecological Statistics and Introduction to Program R, Kearney & Lincoln, NE \hfill 2017-2018
1. __Co-organizer__ Symposium: Opportunities and Challenges in Big Data Ornithology. North American Ornithological Conference V, Washington, D.C., 2016