---
output: 
  pdf_document:
      latex_engine: pdflatex
      template: cv-latex.tex
  # md_document:
  #   variant: markdown_github
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding,
         output_format = "all") })
geometry: margin=.7in
title: "NCEAS 3-g"
author: JESSICA L. BURNETT
orcid:  0000-0002-0896-5099
fontawesome: yes
email: jburnett@usgs.gov
# email: jessicaleighburnett@gmail.com
github: trashbirdecology
twitter: trashbirdecol
phone: "+1 352 792 5425"
updated: yes
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue(munsell)
# linkcolor: maroon
---
# Education  
**Ph.D., Natural Resource Sciences, Specialization Applied Ecology** \hfill 2015 - 19  
School of Natural Resources, University of Nebraska-Lincoln, Nebrasaka USA

**M.Sc., Wildlife Ecology & Conservation** \hfill 2013 - 15  
Department of Wildlife Ecology & Conservation, University of Florida, Florida USA

**B.Sc. Wildlife Ecology & Conservation** \hfill 2010 - 13  
Department of Wildlife Ecology & Conservation, University of Florida, Florida USA

# Professional Experience
**Research Ecologist & Mendenhall Postdoctoral Fellow**  \hfill September 2019 - present  
Science Analytics and Synthesis, Core Science Systems  
U.S. Geological Survey, Lakewood, Colorado, USA

**Graduate Research Assistant**   \hfill August 2015 - August 2019  
Nebraska Cooperative Fish & Wildlife Research Unit   
School of Natural Resources  
Department of Agronomy & Horticulture  
University of Nebraska-Lincoln, Nebraska, USA

**Young Scholar**    \hfill May 2018 - September 2018  
Applied Systems Analysis Research Group  
International Institute for Applied Systems Analysis 
Laxenburg, Austria

**Graduate Teaching & Research Assistant**   \hfill August 2013 - August 2015   
Department of Wildlife Ecology & Conservation  
University of Florida, Florida, USA

**Geospatial Analyst Intern**  \hfill April 2012 -  August 2012  
Florida Fish and Wildlife Research Institute
Gainesville, Florida, USA

**Research Assistant**  \hfill January 2011 -  April 2012  
Avian Ecology and Conservation Lab
University of Florida, Gainesville, FL, USA

**Crew Leader, Smithsonian Fellow**  \hfill   April-September 2011 and April-September 2013  
Neighborhood Nestwatch Program  
Smithsonian Migratory Bird Center, Gainesville, FL, USA

# Publications 
1. **Burnett, J.L.**, L.S. Wszola, and G. Palomo-Munoz. 2019. bbsAssistant: An R package for downloading and handling data and information from the North American Breeding Bird Survey. Journal of Open Source Software, 4(44), 1768, DOI: [10.21105/joss.01768](https://doi.org/10.21105/joss.01768)

1. Donovan, V.M., **J.L. Burnett**, C.H. Bielski, H.E. Birge, R. Bevans, D. Twidwell, and C.R. Allen. 2018. Social-ecological landscape patterns predict woody encroachment from native tree plantings in a temperate grassland *Ecology and Evolution* 8(19): 9624-9632 DOI:10.1002/ece3.4340

1.  **Burnett, J.L.**, K.L. Pope, A. Wong, C.R. Allen, D.M. Haak, B.J. Stephen, and D.R. Uden. 2018. Thermal tolerance limits of the invasive Chinese mysterysnail *Bellamya chinensis* and implications for management". *American Malacological Bulletin* 36(1): 140-144 DOI:10.4003/006.036.0106   

1. Roberts, C.P., D. Twidwell, **J.L. Burnett**, V.M. Donovan, C. Wonkka, C.H. Bielski, A.S. Garmestani, D.G. Angeler, T. Eason, B.W. Allred, M.O. Jones, D.E. Naugle, S. Sundstrom, C.R. Allen . 2018. Early warnings for state transitions. *Rangeland Ecology and Management* DOI:10.1016/j.rama.2018.04.012     

1. La Sorte, F.A., C.A. Lepczyk, **J.L. Burnett**, A. Hurlbert, M. Tingley, and B. Zuckerberg. 2018. Opportunities and challenges for big data ornithology. *The Condor* 120(2): 414-426 DOI:0.1650/CONDOR-17-206.1

1. Chuang, W.C., A.S. Garmestani, T. Eason, T.L. Spanbauer, H.B. Fried-Peterson, C. Roberts, S. Sundstrom, **J.L. Burnett**, D. G. Angeler, B. Chaffin, L. Gunderson, D. Twidwell, C.R. Allen. 2018. Enhancing quantitative approaches for assessing ecological and community resilience. *Journal of Environmental Management* 213: 353-362 DOI:10.1016/j.jenvman.2018.01.083    

1.  **Burnett, J.L.**, C.R. Allen, C.P. Roberts, M.Bomberger Brown, and M.P. Moulton. 2017. Eurasian Tree Sparrow (*Passer montanus*) range expansion in North America. *Biological Invasions* 19(1): 5-9 DOI:10.1007/s10530-016-1273-4  

1.  **Burnett, J.L.** and K.E. Sieving. 2016. Songbird distress call as a detection enhancement method and application to Red-shouldered Hawks (*Buteo lineatus*). *Florida Field Naturalist* 44(4):157-168      

1. C.R. Allen, H.E. Birge, S.L. Bartlet-Hunt, R.A. Bevans, **J.L. Burnett**, B.A. Cosens, X. Cai, A.S. Garmestani, I. Linkov, E.A. Scott, M.D. Solomon, and D.R. Uden. 2016. Avoiding decline: Fostering resilience and sustainability in midsize cities. *Sustainability* 8(9):844-868 DOI:10.3390/su8090844   

1. **Burnett, J.L.** and M.P. Moulton. 2015. Recent trends in House Sparrow (*Passer domesticus*) distribution and abundance in Gainesville, Alachua County, Florida. *Florida Field Naturalist* 43(4):167-172   

# Code and Software
1. **Burnett, J.L.**, L.S. Wszola, and G. Palomo-Munoz. 2019. [`bbsAssistant`](https://github.com/TrashBirdEcology/bbsAssistant): An R package for downloading and handling data and information from the North American Breeding Bird Survey: U.S. Geological Survey software release. DOI: [10.5066/P93W0EAW](https://doi.org/10.5066/P93W0EAW).
1. Price, N.B., C. Chizinski, and **J.L. Burnett**. `radsets`. An R package for interactive, network-based visualizations of overlapping sets.  [Github:natbprice/radsets](https://natbprice.github.io/radsets/)
1. **Burnett, J.L.**, N.B. Price, and A.J. Tyre. [`distanceTravelled`](https://github.com/TrashBirdEcology/distancetravelled). An R package for calculating the distance traveled by a multispecies community along a time series. 
1. Price, N.B. and **J.L. Burnett**. `tvdiff`.  An R package for numerical differentiation of noisy, non-smooth data. [Github:natbprice/tvdiff](https://github.com/natbprice/tvdiff) 
1. **Burnett, J.L.**, N.B. Price. [`regimeDetectionMeasures`](https://github.com/TrashBirdEcology/regimedetectionmeasures).. An R package for calculating univariate and multivariate regime detection methods using community time series.  

# Book Chapters
1. **Burnett, J.L.** and C.R. Allen. 2020. Continental Analysis of Invasive Birds:  North America *in* Downs, C.T. and Hart, L.A. (eds) Global trends and impacts of alien invasive birds. CABI, Wallingford, U.K. 

# Relevant Manuscripts in Prepartion 

1. *Burnett, J.L.*, C. Hou, T. Wellman, et al.. Improving the usability and utility of digital applications in ecology and conservation. Intended for submission to *Ideas in Ecology and Evolution*. 

1. **Burnett, J.L.**, N.B. Price, A.J. Tyre,  D.G. Angeler, T. Eason, D. Twidwell., and C.R. Allen. Deconstructing the steps for calculating Fisher Information as a measure of abrupt change in ecological systems. *Under revision for resubmission*

1. **Burnett, J.L.**, L. Wszola, N. Mirochnitchenko, E. Stuber, M. Bomberger Brown, C.R. Allen, D. Twidwell, and J. Carroll. Large-scale crop patterns influence Gray Partridge (*Perdix perdix*) site occupancy in North America. *Using integrated occupancy modelling to understand patterns and drivers of range shifts.*

# Grants
- Pedersen, E., **J.L. Burnett**, G. Simpson, C. Bahlai. 2020. Working group: Creating a unified approach to evaluate regime shift detection methods.  \hfill __$12,400 CAD__ 
- Mendenhall Postdoctoral Fellowship. 2019. U.S. Geological Survey.  \hfill __~$222,000__

## Under Review  
- Pedersen, E., **J.L. Burnett**, G. Simpson, C. Bahlai. Creating a unified approach to evaluate regime shift detection methods. Powell Center Synthesis Working Group, U.S. Geological Survey \hfill __$166,642__ \hfill   


# Notable Honors & Awards
- [Meritorious Graduate Student](http://snr.unl.edu/aboutus/what/awardscomplete.asp). 2018. School of Natural Resources, UNL \hfill __$500__
- National Academy of Sciences research award 2018. \hfill __$5,500__
- Participant, [NIMBiOS Workshop for Women in Mathematical Biology](http://www.nimbios.org/education/WS_wwmb) 2018. \hfill __$900__
- Big Ten Academic Alliance Traveling Scholar. 2018.    
- Resilience Alliance Young Scholar, The Resilience Alliance. 2015-2017. 

# Relevant Instruction
**Co-instructor** Introduction to Applied Ecological Statistics, Kearney, NE \hfill 2017
- Week-long workshop for employees of the Nebraska Game and Parks Commission employees

**Instructor** Introduction to Prorgam R \hfill 2017
- Designed and taught a series of half-day workshops for graduate students
- Basics of data management and analysis using Program R

**Guest Lecturer** Module: using citizen science data to understand ecological invasions; Course: Avian Invasions  \hfill 2016
- Designed and taught series of lectures on citizen science data use and applications

**Teaching Assistant** Ecological Statistics, Department of Wildlife Ecology & Conservation, University of Florida \hfill 2015

<!-- # Organized Sessions and Symposia  -->
<!-- 1. Burnett, J.L. and J.A. Royle. Using the integrated modelling framework to bridge science and decision making: advances, applications, and opportunities.  Ecological Society of America conference \hfill 2020 -->
<!-- 1. LaSorte, F.A., C.A. Lepczyk, *J.L. Burnett*. Opportunities and Challenges in Big Data Ornithology. Co-organizer with. North American Ornithological Conference V, Washington, D.C. \hfill 2016 -->

<!-- # Relevant Presentations (primary author)   -->
<!-- ## Invited  -->
<!-- 1. Regime Detection Measures for the Pratical Ecologist, Department of Wildlife Ecology & Conservation, University of Florida \hfill 2019 -->

<!-- 1. Detecting abrupt change in bird community time series using distance travelled. *Association for Women in Math Biology Symposium*, Special session "Current Challenges in Mathematical Biology ", Houston, TX  \hfill 2019 -->


<!-- ## Contributed -->
<!-- 1. **Burnett, J.L.**, N.B. Price, and A.J. Tyre. A novel method for tracking ecosystem trajectory and abrupt change in space-time: distance traveled. *International Association for Landscape Ecology*, Oral presentation. Fort Collins, CO, 2019 -->

<!-- 1. **Burnett, J.L.**, R. Crystal-Ornelas, D. Fogarty, K. Hogan, C.R. Allen, M. Bomberger Brown, D. Twidwell, and C.A. Lepczyk. Impacts of non-native birds on native wildlife in urban ecosystems: synthesis of the the evidence?  *Natural Areas Conference*, Oral presentation. Indiana, 2018 -->

<!-- 1. **Burnett, J.L.**. Advances in ecological regime shift detection, *International Institute for Applied Systems Analysis*, Oral presentation. Laxenburg, Austria, 2018 -->

<!-- 1. **Burnett, J.L.**, L. Wszola, N. Mirochnitchenko, E. Stuber, M. Bomberger Brown, C.R. Allen, D. Twidwell, and J.P. Carroll.  Gray partridge distribution in North America: Changing landscapes and environment for an introduced species. Perdix XIV and IUGB, Oral presentation by JPC, Montpellier, -->
<!-- France, 2017 -->

<!-- 1. **Burnett, J.L.**, N.B. Price, A.J. Tyre, T.J. Hefley, C.R. Allen, T. A. Eason, D.G. Angeler,and D. Twidwell. System trajectory and Fisher information as early-warning indicators of ecological regime shifts. *Resilience 2017: Resilience Frontiers for Global Sustainability*, Poster presentation. Stockholm, Sweden, 2017 -->

<!-- 1. **Burnett, J.L.**, Roberts, C.P., Allen, C.R., Angeler, D.G., Twidwell, D., and Tyre, A.J. Using Big Data to Detect Regime Shifts in Space and Time. *North American Ornithological Conference VI*, Poster presentation. Smithsonian Migratory Bird Institute, Washington, D.C., 2016 -->

# Peer Reviewer Service  
- *Bioinvasions Records* (1), *Conservation Biology* (1), *Ecological Informatics*, (2) *Ecological Modelling* (4), *Journal of Molluscan Studies* (2), *Journal of Open Source Software* (1), *PLOS One* (1), *ReScience* (1),  *Wilson Journal of Ornithology* (3), *U.S. Geological Survey selected reviewer* (3)
