---
output: 
  pdf_document:
      latex_engine: pdflatex
      template: cv-latex.tex
  md_document:
    variant: gfm
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding,
         output_format = "all") })
geometry: margin=.7in
title: "Open Grants Advisory Opporunity "
author: JESSICA L. BURNETT
orcid:  0000-0002-0896-5099
fontawesome: yes
email: jburnett@usgs.gov
github: trashbirdecology
phone: "+1 720-730-0974"
# updated: no
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue(munsell)
linkcolor: maroon
linkedin: burnettjl
jobtitle: Research Ecologist & Mendenhall Postdoctoral Fellow
---
**Research Ecologist** (GS-12-3), U.S. Geological Survey, Lakewood, Colorado, USA
September 2019 - present

# Research Interests and Expertise
-   Ecoinformatics
-   Reproducibility and open science
-   Applied statistics
-   Knowledge management for conservation

# Education

**Ph.D.** Natural Resource Sciences University of Nebrsaka-Lincoln   
**M.Sc.** Wildlife Ecology & Conservation, University of Florida   
**B.Sc.** Wildlife Ecology & Conservation University of Florida   
**A.A.** General studies Valencia Community College

# Resaerch Proposals
## Funded 
1. Wee, B., **J.L. Burnett**, S. Aulenbach, W. Teng, R.A. Modeling data and information needs for avian conservation using Neo4j. Earth Science Information Partners Lab \hfill $3388
1. Pedersen, E., **J.L. Burnett**, G. Simpson, C. Bahlai. __2020__. Creating a unified approach to evaluate regime shift detection methods. Canadian Institution for Ecology and Evolution (CIEE)  \hfill __$12,400 CAD__
1. **J.L. Burnett**. __2019-21__. Mendenhall Postdoctoral Research, Core Science Systems Science Analytics and Synthesis, U.S. Geological Survey.  \hfill __~$222,000__
1. International Institute for Applied Systems Analysis (IIASA) [Young Scholar Summer Program](https://iiasa.ac.at/web/home/education/yssp/Young_Scientists_Summer_Program.html). __2018__. Funding sources: National Academy of Sciences and University of Nebraska-Lincoln. \hfill __~$12,500__

## Not Funded  
1. Pedersen, E., **J.L. Burnett**, G. Simpson, C. Bahlai. Creating a unified approach to evaluate regime shift detection methods. Powell Center Synthesis Working Group, U.S. Geological Survey \hfill 2020  <!--__$166,642__  --> 
1. Informing the design and deployment of a conservation tool, USAvian: learning through co-production, synthesizing lessons learned. Community for Data Integration, U.S. Geological Survey \hfill 2020 <!--  __$70,539__  -->
1. Benito, X., C. Bahlai, **J.L., Burnett**, E. Pedersen, and G. Simpson. SESYNC working group proposal.  \hfill  2019  
1. **Burnett, J.L.**. Population Biology Program of Excellence (PoE) Postdoctoral Fellowship, University of Nebraska-Lincoln \hfill 2018  
1. **Burnett, J.L.**, C.R. Allen, G. Sugihara, and H. Ye. Scale mismatches in ecological research and management: consequences and solutions through data management. Powell Center Synthesis Working Group, U.S. Geological Survey   \hfill 2018  
1. **Burnett, J.L.** Mozilla Fellowship for Science \hfill 2016  
1. **Burnett, J.L.** NSF Graduate Research Fellowship   \hfill 2013  


# Select STEM Outreach

- Letters to a Pre-scientist (2018-present)
- Skype a Scientist, Virtual (2017-2021)
- Secured grant to develop on-site nature trail and wildlife viewing opportunities at the Reichert House in Florida (2014-15)
- Science, mathematics, and reading tutor for middle and high school students, Friends of the Micanopy Library, FL (2011-13)

# Select Service 
- Member, Federal Advisory Committee for Avian Knowledge Network (2019-present)
- Member, Communications and Marketing Committee for the North American Breeding Bird Survey 2020 Action Plan (2020-21)
- Co-founder, Natural Resources Diversity Initiative committee, School of Natural Resources (2017)
- [Faculty Advisory Committee](http://snr.unl.edu/employeeinfo/people/committee/facultyadvisory.asp), School of Natural Resources (2016-18) 
- Co-founder, [Institutional membership to the Association for Women in Science](http://news.unl.edu/newsrooms/today/article/university-is-institutional-partner-with-association-for-women-in-science/) (2016)


# Select Fellowships, Honors & Awards
- AAAS Science Technology and Policy Fellowship semi-finalist (finalist selections pending) \hfill (2022)
- Invited workshop participant, Future of Synthesis in Ecology, NCEAS \hfill (2021)
- [Meritorious Graduate Student](http://snr.unl.edu/aboutus/what/awardscomplete.asp) award, School of Natural Resources, UNL \hfill (2018)
- National Academy of Sciences research award  \hfill __$5,500__ (2018)
- Invited Participant, [Workshop for Women in Mathematical Biology, NIMBIOS](http://www.nimbios.org/education/WS_wwmb) \hfill (2017)
- Graduate Fellow, Center for Great Plains Studies, University of Nebraska (2016-18)
- Resilience Alliance Young Scholar, The Resilience Alliance (2015-2017) \hfill (2015-17) 

<!-- ## Peer Review Activity   -->
<!-- - Journal articles: *Bioinvasions Records* (1), *Conservation Biology* (1), *Ecological Informatics* (6), *Ecological Modelling* (4), *Journal of Molluscan Studies* (2), *Landscape and Urban Planning* (2), *PLOS One* (1), *Wilson Journal of Ornithology* (3), *Methods in Ecology and Evolution* (1 in prep) -->
<!-- - Code and software: *Journal of Open Source Software* (3), *ReScience* (1) -->
<!-- - Department of Interior: Abstracts (2), Research Articles (2), Software/code (1), Reports (2) -->


